### ISSUE TITLE
G920 incorrect pedal mapping

### ISSUE THREAD

**Issue by joshnies** [berarma/oversteer#103]
For the Logitech G920 wheel, pedals are being incorrectly mapped for me on both `master` and `0.7.0` release.

How it looks for me:
Accel -> Clutch
Brakes -> Accel
Clutch -> Brakes

Pedals work correctly on `0.6.0` release, but then my steering range is all messed up

**Comment by Hedronmx** [comment]
Was about to report this, is there a way to remap the pedal?

**Comment by berarma** [comment]
I'll fix it soon.
