### ISSUE TITLE
Can't combine accelerator + clutch on Logitech G29

### ISSUE THREAD

**Issue by rockerbacon** [berarma/oversteer#104]
I need to combine accelerator and clutch in a single axis in order to get some older NFS games working but Oversteer doesn't seem to be able to do it despite the option being available. When accelerator + clutch is selected, everything behaves the same as in accelerator + brakes, both within the games and in the Oversteer interface itself.

**Comment by berarma** [comment]
I guess you're using new-lg4ff or the option would be disabled. I've just tested it on my G29 and it's working with the latest new-lg4ff and Oversteer versions.

Which compatibility mode are you using? I'm testing in G29 mode.

**Comment by rockerbacon** [comment]
That's it then, I'm not using new-lg4ff. My bad, should have paid more attention to the readme.

Thanks for the quick response.

**Comment by berarma** [comment]
Currently there's no way to detect the available options so it's always enabled. I'll try to fix it in future versions.
