### ISSUE TITLE
Ubuntu 20.04.2 Thrustmaster T300RS

### ISSUE THREAD

**Issue by sayapinsergej** [berarma/oversteer#105]
Oversteer sees my database but immediately a warning appears: You don't have the required permissions to change your wheel settings

**Comment by berarma** [comment]
Did you install Oversteer as explained in the Readme? It should have installed the required udev files. A reboot is needed to make it work.

**Comment by sayapinsergej** [comment]
Yes, I installed it as described in the Readme, disconnected the database and rebooted

**Comment by sayapinsergej** [comment]
T300RS

**Comment by berarma** [comment]
Did you install hid-tmff2 and is it working?

**Comment by sayapinsergej** [comment]
hid-tmeff2 has been installed, but I don't know if it works. how to check it?

**Comment by berarma** [comment]
See #106.
