### ISSUE TITLE
Loading profile on steam game launch

### ISSUE THREAD

**Issue by fuzunspm** [berarma/oversteer#11]
Hi,

First of all thank you very much for this awesome software. It really works without an issue.

My only issue here is about mentioned line in Readme file:

`You can configure game launchers to run oversteer to load a profile or change settings so that it automatically configures the wheel when the game runs.`

But I couldn't find it from --help on how to do this for steam games. I have a profile named "gg" and i want to load it as soon as i launch Assetto Corsa Comp. on steam (via proton). I tried `oversteer -p gg` but that didn't work

Thanks

**Comment by berarma** [comment]
This is not specific to this application so I didn't include any details. For Steam you should write the following line in the launch options:

`oversteer -p gg /dev/input/by-id/usb-Logitech_G29_Driving_Force_Racing_Wheel-event-joystick && %command%`

Don't forget to specify the path to your wheel device. The second part of the command launches the game.
