### ISSUE TITLE
Logitech G920 product ID in udev rule doesn't match product ID from lsusb

### ISSUE THREAD

**Issue by einsJannis** [berarma/oversteer#111]
For some reason the product ID for the Logitech G920 in the udev rule does not match what `lsusb` reports as the product ID of my Logitech G920.
`lsusb` reports:
```
Bus 001 Device 002: ID 046d:c261 Logitech, Inc. G920 Driving Force Racing Wheel for Xbox One
```
and the udev rule states:
```
# Logitech G920 Driving Force Racing Wheel
SUBSYSTEMS=="hid", KERNELS=="0003:046D:C262.????", DRIVERS=="logitech-hidpp-device", RUN+="/bin/sh -c 'cd %S%p/../../../; chmod 666 range'"
```

My steering wheel worked before I decided to reinstall my system and after reinstalling my steering wheel wasn-t recogniyed by my computer anymore. I`m not sure this is the problem though, because simply changing the rule doesn't make it work.

**Comment by berarma** [comment]
Your wheel is in XBox mode. Your system should automatically change the wheel to PC mode. You can try installing the package `usb-modeswitch` and see if that fixes it after a reboot. If it still doesn't work you can look for instructions to do it manually but I'd recommend you to look for help for your distro or report a bug.
