### ISSUE TITLE
Thrustmaster T300 F1 wheel attachment

### ISSUE THREAD

**Issue by otsku** [berarma/oversteer#117]
I have Thrustmaster T300 F1 wheel attachment and when I change the compatibility mode to "T300RS with F1 wheel attachment" in oversteer it will just stop responding. After killing oversteer and restarting it, it wont recognize my wheel unless I unplug usb cable. I'm willing to provide more debug info if you just tell me how do I gather it.

**Comment by otsku** [comment]
To be clear F1 wheel works on windows and it also works on "T300RS base" compatibility mode.

**Comment by berarma** [comment]
It will probably change its product id. I need the wheel info from lsusb.

**Comment by otsku** [comment]
Here is lsusb when I have not changed compatibility mode:
Bus 001 Device 010: ID 044f:b66e ThrustMaster, Inc. Thrustmaster T300RS Racing wheel

Here is lsusb when I have changed compatibility mode:
Bus 001 Device 011: ID 044f:b66f ThrustMaster, Inc. Ferrari F1 Wheel Advanced T300

**Comment by berarma** [comment]
I've pushed a new commit with the wheel id. Please, test it.

**Comment by otsku** [comment]
I still got the same problem. It seems like my wheel is in fact in advanced mode aka F1 wheel mode, but oversteer just wont recognize it. I tested this in dirt rally 2.0 input reporting page.

**Comment by berarma** [comment]
Sorry, I forgot to say you need to reinstall Oversteer and reboot your computer.

**Comment by otsku** [comment]
I did reinstall Oversteer. First uninstalled like it says in readme and then installed again. I did reboot my computer before reinstalling and before I plugged in my wheel.

**Comment by berarma** [comment]
You have to reboot your computer AFTER reinstalling.

**Comment by otsku** [comment]
Oh my bad. I wrote wrong. I did reboot my computer after uninstalling and after reinstalling. Sorry

**Comment by berarma** [comment]
Well, my bad, I thought it was all done. Try again. It should work now.

**Comment by otsku** [comment]
Now issue seems to be solved. It also worked when I just deleted oversteer-master folder, downloaded new files and ran the build script without reboots or that reload command from readme. Thanks for fixing it. You are doing fine job.

**Comment by berarma** [comment]
The first reboot was needed to fix one part of the issue. Thanks!
