### ISSUE TITLE
Oversteer app won't launch

### ISSUE THREAD

**Issue by Peltori** [berarma/oversteer#119]
I installed oversteer from AUR and it complains about locale not found or something.
Traceback (most recent call last):
  File "/usr/bin/oversteer", line 48, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.10/locale.py", line 620, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Here is the error that i get when trying to launch it from terminal. I'm using arch linux and 6.0.1 linux kernel

**Comment by berarma** [comment]
Probably a bad locale on your system. Check your generated locales and the locales in use.

**Comment by Peltori** [comment]
I am using en_US.UTF-8 locale but still the same error when trying to start the app

**Comment by berarma** [comment]
Can you please check #87?

The locale you're using must have been generated in your system. You can check configured locales with `locale -a` and generate locales with `locale-gen`.

**Comment by Peltori** [comment]
Fixed it, KDE was messing my locale up. It was trying to generate en_FI locale which does not exist :D sorry for causing problems and headache for you. Thanks for help!

**Comment by berarma** [comment]
No prob.
