### ISSUE TITLE
Changing language to English assumes en_US (and that the other selectable languages locale's are generated)

### ISSUE THREAD

**Issue by gripped** [berarma/oversteer#12]
Hi 

Great program. And new-lg4ff as well. Fantastic work.

Just looking around the gui I changed the language in the preferences to English.
Next time I tried to start the program
```$ oversteer 
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/oversteer/gui.py", line 340, in save_preferences
    locale.setlocale(locale.LC_ALL, (language, 'UTF-8'))
  File "/usr/lib64/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Found the config file and saw
```
locale = en_US
```
Changing that to en_GB, or back to nothing, allowed the program to start.
I don't have en_US.
Very minor problem. I almost didn't report it. But then decided you'd probably rather know. If you don't already?

This is on Gentoo btw. At some point I'll try and make ebuilds for both new-lg4ff and oversteer.
Do you have any intention of getting the driver accepted into the kernel ?
Thanks

**Comment by berarma** [comment]
Hi.

That's how it works. The preferred way to select the language is through the system locale or LC_LANGUAGE environment variable. The current language selection method isn't the best but it works for some.

I may take a look to try to improve it but I'd prefer everyone used one of the preferred methods.

> Do you have any intention of getting the driver accepted into the kernel ?

Yes, at some point when I get some more free time.

**Comment by gripped** [comment]
I have nothing but time atm. Lockdown :(
I have made the gentoo ebuilds I mentioned for new-lg4ff and oversteer.
https://github.com/gripped/Logitech-wheel-ebuilds

I will look at the code around switching locales and attempt to add a a little sanity checking. If I manage it I'll send pull request.

**Comment by berarma** [comment]
> I have nothing but time atm. Lockdown :(
> I have made the gentoo ebuilds I mentioned for new-lg4ff and oversteer.
> https://github.com/gripped/Logitech-wheel-ebuilds

Thanks!

> I will look at the code around switching locales and attempt to add a a little sanity checking. If I manage it I'll send pull request.

I have no ideas right now, I'd have to learn a bit more about gettext, locales and python. I think the problem was that I had to use locales that existed in the system. I don't know how to get around that.

**Comment by gripped** [comment]
> I think the problem was that I had to use locales that existed in the system. I don't know how to get around that.

Me neither. :) 
But a check could be made that the locale a user is switching to exists. is generated. And then if it doesn'trefuse to switch whilst advising in a dialog which locale needs to be generated.
ATM there's no error in the GUI, Only if started from the command line. And then the next time you start the program it fails to start. 
I guessed pretty much straight away what the problem was. Someone newer to Linux might struggle.
Like I say: I have time :( I'll take a look. On the Barcardi now :)

**Comment by berarma** [comment]
Handling languages inside the application has been tricky for me, that's why I didn't want to put much work on it. I still think using the system settings should be the right solution but they aren't as configurable as they should yet. So we need this workaround. Thanks for looking into it.

**Comment by gripped** [comment]
Like I say KDE ignores the change to locale set in oversteer. Not sure what gnome does ?
I did install the Valencian locale for testing. Even with in on my system changing to it resulted in no change when I restarted the app. Worked under openbox.

But the main thing for me was to stop the program failing to start. That's been achieved I hope

**Comment by berarma** [comment]
> Like I say KDE ignores the change to locale set in oversteer. Not sure what gnome does ?
> I did install the Valencian locale for testing. Even with it on my system changing to it resulted in no change when I restarted the app. Worked under openbox.

It doesn't work in Gnome neither. I thought that was a Python/GTK thing. Why could it work in Openbox but not KDE/Gnome? I'd like to know.
