### ISSUE TITLE
Thrustmaster TX support

### ISSUE THREAD

**Issue by Austin-2** [berarma/oversteer#120]
Hello,

I was looking for support for a Thrustmaster TX wheel. Mine is the Ferrari 458 wheel, but it is technically a Thrustmaster TX.

https://support.thrustmaster.com/en/product/txracingwheel-en/

I was able to get the wheel working with tmdriv, but it did not have FFB. The pedals were acting up in F1 2020 but I believe I needed to configure it.

I would love if there would be support for my wheel on Linux!

thanks!

**Comment by berarma** [comment]
Please, read the [README](https://github.com/berarma/oversteer/blob/master/README.md).

I can add your wheel to the list of supported wheels in Oversteer and you will be able to test it. But if you want FFB or other features, you need a driver. There are two drivers listed for Thrustmaster. You should write to them to ask if you will could be supported.

In the mean time, if you want to see your wheel appear in Oversteer, please send me the IDs list for your wheel with the `lsusb` command.

**Comment by Austin-2** [comment]
I can add that later today.  Curious if you would know this, I do have drivers with [tmdrv](https://github.com/her001/tmdrv). It has button, wheel and pedal support, but no ffb. So should I expect Oversteer to be able to configure the buttons, steering and pedal but it won't enable ffb?

**Comment by berarma** [comment]
I think tmdrv isn't longer needed with a modern Linux kernel. You will be able to use buttons, steering and pedals in Oversteer but it won't enable FFB.

**Comment by Austin-2** [comment]
Bus 001 Device 004: ID 044f:b664 ThrustMaster, Inc. Thrustmaster TX GIP Racing Wheel

**Comment by berarma** [comment]
It's added. I would contact one of the Thrustmaster driver projects in the README. They might be able to help.
