### ISSUE TITLE
support for additional Thrustmaster FFE

### ISSUE THREAD

**Issue by peterlopen** [berarma/oversteer#122]
hi,

there are some additional effects supported in hid-tmt300rs driver which are currently not displayed in oversteer (there are part of windows control panel too):
FF_PERIODIC https://github.com/Kimplul/hid-tmff2/blob/e2dd7bdc3a22ac8b8551db4154fa36fcc631b402/hid-tmt300rs.c#L29
FF_CONSTANT https://github.com/Kimplul/hid-tmff2/blob/e2dd7bdc3a22ac8b8551db4154fa36fcc631b402/hid-tmt300rs.c#L23
Just wondering if it would make sense and be possible to add those to oversteer in case detected wheel is t300rs. Settings recommendations for TM wheels usually mentions those.

thank you.

regards
peter

**Comment by berarma** [comment]
I don't think `hid-tmff2` has different gain settings for constant and periodic effects. Additionally, I don't think this is as useful as it seems.

Constant and periodic effects share the same basics. Sometimes constant effects are played using periodic effects and vice versa. They are essentially the same kind of force and altering them separately would change the way the FFB was meant to be. It sounds like a red flag for poorly implemented FFB effects or wrong user expectations.

We would need to implement this feature in the drivers first then in Oversteer. I'm sorry but I don't think it's worth the work for the reasons above.

**Comment by peterlopen** [comment]
Thanks for your explanation. 
Honestly, I do not know much about those two effects, my reasoning is based on what I found e.g. [here](https://www.briankoponen.com/assetto-corsa-thrustmaster-tx-t300-settings/) and [here](https://www.isrtv.com/forums/uploads/monthly_2016_06/t300rs.jpg.1af6f9c8b134e156ad5d9647bc109594.jpg).
Also there are two different methods to set those in driver code: [t300rs_update_periodic](https://github.com/Kimplul/hid-tmff2/blob/e2dd7bdc3a22ac8b8551db4154fa36fcc631b402/hid-tmt300rs.c#L830) vs [t300rs_update_constant](https://github.com/Kimplul/hid-tmff2/blob/e2dd7bdc3a22ac8b8551db4154fa36fcc631b402/hid-tmt300rs.c#L618).

I got your reasoning, just wondering why is that case in TM control panel. With installing TM drivers in wine prefix, wheel now feels good with settings as there are present in oversteer currently, so I am fine with your conclusion. thank you.

**Comment by berarma** [comment]
Periodic isn't really an effect type, it's a group of effects that have a repeating pattern, sine, square, triangular,... Also, having those methods in the code doesn't mean there's an external gain setting that can be tuned by the user.

If you want to avoid clipping you need only the global gain. Having separate gains for constant and periodic wouldn't help, it would probably make it worse.

I don't know what the TM drivers are doing and I wish we would, but I don't think it's about those gain settings. Maybe something else.

And if you want a suggestion, rFactor 2 is the reference for best FFB and driving feel. AC is not bad, but it's not as good. ;)

**Comment by peterlopen** [comment]
thanks for recommendation, @berarma  . based on proton DB it should also work perfectly with t300 rs. will grab it on next sale :)
