### ISSUE TITLE
T300RS and profiles

### ISSUE THREAD

**Issue by sayapinsergej** [berarma/oversteer#123]
Hello! My T300RS steering wheel with the driver installed works fine. In oversteer, I can fully configure it as needed. But I can't create or save my profile. Is the save button inactive? How to do it? How do I save my settings?

**Comment by sayapinsergej** [comment]
Hello? My T300RS steering wheel with the driver installed works fine. In oversteer, I can fully configure it as needed. But I can't create or save my profile. Is the save button inactive? How to do it?

**Comment by berarma** [comment]
> Hello! My T300RS steering wheel with the driver installed works fine. In oversteer, I can fully configure it as needed. But I can't create or save my profile. Is the save button inactive? How to do it? How do I save my settings?

Do you give it a name?

**Comment by sayapinsergej** [comment]
Yes, ![image](https://user-images.githubusercontent.com/107651826/203496496-60113728-5d43-4464-a85d-2aa4e2dc8853.jpeg)

**Comment by berarma** [comment]
Ah, sorry. That "Save" button is used after the profile has been created to save changes. You have to click the "New" button to create a new profile.

**Comment by sayapinsergej** [comment]
ok, then where is the create button?

**Comment by berarma** [comment]
In the right column, it's labelled "New".

**Comment by sayapinsergej** [comment]
I'm sorry, but I still don't understand. So: I press the New button, sign, and what's next? I can't save or export...

**Comment by berarma** [comment]
> I'm sorry, but I still don't understand. So: I press the New button, sign, and what's next? I can't save or export...

- Type the name of the profile.
- Press the New button.
- Select the profile in the dropdown above next to the Save button.

I hope it makes sense.

**Comment by sayapinsergej** [comment]
![image](https://user-images.githubusercontent.com/107651826/203809965-4813e546-44cb-44d0-9e20-dd9fe5feeac0.jpeg)

**Comment by sayapinsergej** [comment]
I don't have a create button

**Comment by sayapinsergej** [comment]
UPD: I figured it out, thank you, the question can be closed!

**Comment by berarma** [comment]
OK. The intention is that you can load and save changes to a profile without using the profiles tab. The profiles tab is only for all the other operations supposedly not used so often.
