### ISSUE TITLE
Continuous scrolling [Accessibility]

### ISSUE THREAD

**Issue by lifeinchords** [berarma/oversteer#129]
Hi there,

Is it possible to use or customize these drivers to use pedals as a controller for scrolling in browsers and other native MacOS/PC/Linux applications? There are foot switches that can be programmed as page up/page down, but they are not continuous. 

Thank you

**Comment by berarma** [comment]
Hi. This is not a driver, it's a Linux desktop application to test and configure wheel devices through their drivers.

In the Linux case, you seem to need some app that can remap udev events from one device to one another.

**Comment by lifeinchords** [comment]
Thank you for letting me know, I'll continue investigating
