### ISSUE TITLE
combined pedals in T150 pro

### ISSUE THREAD

**Issue by albfan** [berarma/oversteer#136]
Looks thrustmaster options are slightly different than provided by oversteer, only two modes, separate (default) and combined: See https://github.com/scarburato/t150_driver/issues/40 for analysis

![227702523-eba0ff02-46ff-42d4-a88b-32f415790280](https://user-images.githubusercontent.com/220968/227708169-d3be0522-5d1e-47e9-9a81-14bb21bce713.png)
![227702524-ff090702-5cda-4fa4-acfd-9d4400615bda](https://user-images.githubusercontent.com/220968/227708170-e568c747-77f9-4738-b2e0-422f3f4bee92.png)

I'm reading https://github.com/berarma/oversteer/issues/47 carefully to understand how oversteer deals with combined pedals.

Should this make pedals config to support modes from vendor/product? I'm starting hid_t150 file property for this in https://github.com/scarburato/t150_driver/issues/41

Any help with this would be appreciated, overall if vendor/product implementation makes sense

**Comment by berarma** [comment]
All we need is that the TM driver creates a combine_pedals sysfs entry. Writing '0' to that entry would set the feature off, writing '1' would set it on. Oversteer detects that the entry exists and uses it.

When that's done we should change permissions to the file in the udev rules. Also, implementing a way to check for throttle/clutch combine option availability would be convenient.

**Comment by albfan** [comment]
ok, will check if device remember the config to implement that. if no probably we would need a different implementation. Let's see.

**Comment by albfan** [comment]
From https://github.com/scarburato/t150_driver/issues/41, combined pedals on T150 driver seems to be a software implementation. So I'm unsure if this makes sense to be implemented.

I don't know if other drivers (like logitech) are doing the same, provide a software implementation that remaps axis to expose this feature (combine pedals)

By now I close this, as t150 driver is not expected to implement this. Combine pedals looks to me a feature to be provided by game or game manager (like steam)

I can implement in t150 driver if there's no good solution outside the driver anyway.

Closing by now
