### ISSUE TITLE
How to launch oversteer profile with a steam game?

### ISSUE THREAD

**Issue by s7relok** [berarma/oversteer#14]
Hello,

Nice software ! I already configured a profile for F1 2019 but unfortunately I can't launch the game with a profile.

Tried GUI ON and launching the game with steam, the (broken) managing of FFB of the game takes command

Tried in launch options /usr/local/bin/oversteer -p F12019 %command% , the game is not starting

Tried /usr/local/bin/oversteer -p F12019 -- %command% and it's not launching too.

Can we have additional information to launch the game with oversteer profile active?

**Comment by berarma** [comment]
Hi @s7relok:

You need to tell which device,for example:
```/usr/local/bin/oversteer -p F12019 /dev/input/by-id/whatever -- %command%```

I'm planning to make it optional when there's just one wheel connected but by now it's required.
