### ISSUE TITLE
Accelerator+Brakes Function Deactivating on Its Own

### ISSUE THREAD

**Issue by JacekLeszczynski** [berarma/oversteer#140]
Here's an example bug report for the issue you described in Oversteer:

Title: Accelerator+Brakes Function Deactivating on Its Own

Description: I am experiencing an issue with the Accelerator+Brakes function in Oversteer. After a certain amount of time playing, the function deactivates on its own. I have to save the game state, exit the game, and reactivate the function in Oversteer before I can resume play. This issue occurs consistently and disrupts my gameplay.

Steps to reproduce:

Open Oversteer and enable the Accelerator+Brakes function.
Start playing a game that supports the function.
After a certain amount of time playing, the function deactivates on its own.
Save the game state and exit the game.
Reopen Oversteer and reactivate the Accelerator+Brakes function.
Resume playing the game.
Expected behavior: The Accelerator+Brakes function should remain enabled throughout the duration of gameplay.

Actual behavior: The function deactivates on its own after a certain amount of time playing.

Additional information: I am using Oversteer version [insert version number] on [insert operating system]. My input device is a [insert device name] connected via [insert connection type]. I have tried disconnecting and reconnecting the device, but the issue still occurs.

**Comment by berarma** [comment]
This could be due a disconnect of the device. Please, check the ouput of the dmesg command and see if the wheel has disconnected and reconnected when this happens. It could be a faulty cable or a loose power plug.

Which wheel do you have? Are you using new-lg4ff? Which driver version?

**Comment by JacekLeszczynski** [comment]
I have a Logitech G29 wheel. I'm using new-lg4ff version 0.3.3.r29. I'll check the connections, and if the problem occurs again, I'll pay attention to what the "dmesg" command outputs. Thank you for the quick response.

**Comment by JacekLeszczynski** [comment]
It turned out that my steering wheel works after being plugged into a different USB port. This helped. I wouldn't have thought of this solution if it weren't for the suggestion I received. Thank you very much for your response. The issue can be closed now. Thanks!
