### ISSUE TITLE
Thrustmaster T80 - No device available

### ISSUE THREAD

**Issue by heater19** [berarma/oversteer#142]
~$ oversteer
No device available.
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3/dist-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3/dist-packages/oversteer/combined_chart.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 57, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 25, in <module>
    from matplotlib import _blocking_input, docstring, projections
  File "/usr/lib/python3/dist-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/fox81linux/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/fox81linux/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 22, in <module>
    from matplotlib import _api, cbook, _docstring, _preprocess_data
ImportError: cannot import name '_docstring' from 'matplotlib' (/usr/lib/python3/dist-packages/matplotlib/__init__.py)

---------
the lsusb output shows the ID 044f:b668 ThrustMaster, Inc. Thrustmaster T80

I realize from the readme file that the T80 is not one of the wheels included in the program, but I was hoping that it would at least be usable without FFB.

**Comment by berarma** [comment]
Yes, I can add it so you can test what works.

**Comment by heater19** [comment]
ok, so tried it out again after the update and got this error message:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3/dist-packages/oversteer/application.py", line 103, in run
    model = Model(device)
  File "/usr/lib/python3/dist-packages/oversteer/model.py", line 48, in __init__
    self.set_device(device)
  File "/usr/lib/python3/dist-packages/oversteer/model.py", line 56, in set_device
    self.update_from_device_settings()
  File "/usr/lib/python3/dist-packages/oversteer/model.py", line 91, in update_from_device_settings
    self.data.update(self.read_device_settings())
  File "/usr/lib/python3/dist-packages/oversteer/model.py", line 76, in read_device_settings
    'ff_gain': self.device.get_ff_gain(),
  File "/usr/lib/python3/dist-packages/oversteer/device.py", line 215, in get_ff_gain
    if ecodes.FF_GAIN in capabilities[ecodes.EV_FF]:
KeyError: 21

------
the wheel is attached to the computer, any idea what this could mean?

thanks

**Comment by heater19** [comment]
any update on the error message above or should I open a new issue?

**Comment by berarma** [comment]
I'll take a look when I can. I think it fails because there's no FFB available but I'll fix it. It should work anyway.

**Comment by berarma** [comment]
Can you test the latest commit in the master branch.

**Comment by heater19** [comment]
ok, so when trying to start the program with the oversteer -g command, i get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 53, in <module>
    sys.exit(app.run(sys.argv))
  File "/usr/lib/python3/dist-packages/oversteer/application.py", line 131, in run
    from oversteer.gui import Gui
  File "/usr/lib/python3/dist-packages/oversteer/gui.py", line 20, in <module>
    from .combined_chart import CombinedChart
  File "/usr/lib/python3/dist-packages/oversteer/combined_chart.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 57, in <module>
    from matplotlib.figure import Figure, figaspect
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 25, in <module>
    from matplotlib import _blocking_input, docstring, projections
  File "/usr/lib/python3/dist-packages/matplotlib/projections/__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/home/fox81linux/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/home/fox81linux/.local/lib/python3.10/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 22, in <module>
    from matplotlib import _api, cbook, _docstring, _preprocess_data
ImportError: cannot import name '_docstring' from 'matplotlib' (/usr/lib/python3/dist-packages/matplotlib/__init__.py)

-------------------
I checked and matplotlib is installed with the python packages, but I am unclear if that is the problem;

there is progress though, on the command line I can now enter commands like 'oversteer --start-manually' or 'oversteer --device /dev/input/event3'; and it won't throw an error.  
So I was thinking that maybe I can configure the wheel via the command line without the gui;  but I'm not sure how;
In a running game, the buttons on the wheel are recognized, but the motions of the wheel and pedals are not;

thanks again for your help in this;

**Comment by berarma** [comment]
It seems you have a mix of system packages and user packages which might not be compatible. You might have a second set of matplotlib dependencies in `/home/fox81linux/.local/lib/python3.10/site-packages/`. Can you try moving this to another place so they aren't found?

**Comment by mmarusiak** [comment]
hey, I've same issue oversteer itself seems working right, but it can't detect T80 wheel. 
![image](https://github.com/berarma/oversteer/assets/20907620/afa6d914-cb97-4f38-80e3-ce988e2df0b3)

**Comment by berarma** [comment]
> hey, I've same issue oversteer itself seems working right, but it can't detect T80 wheel.
> 
> ![image](https://user-images.githubusercontent.com/20907620/255403716-2eebb740-815f-4d65-87e2-b72c9f6d7b08.png)

It doesn't look like the same issue. Are you getting any errors when running from console?

Have you installed the latest in the master branch?

**Comment by mmarusiak** [comment]
Yeah, I installed latest master branch, installation went as expected, but steering wheel is not detected anywhere in program. It's detected as gamepad in games (f.e. in F1 22), so I thought installing oversteer maybe would fix it.

**Comment by mmarusiak** [comment]
I'm not getting any issues in console (or I don't see them - I'm running it just from "desktop app").

**Comment by berarma** [comment]
It won't make the games detect the wheel correctly. Can you list the USB ids with `lsusb`?

**Comment by mmarusiak** [comment]
on ``lsusb`` I can see all my devices including T-80:
``Bus 001 Device 005: ID 24c6:5b00 Thrustmaster Ferrari 458 Racing Wheel``
(It's t-80 f458 version but drivers are the same I'm pretty sure).

**Comment by berarma** [comment]
> on ``lsusb`` I can see all my devices including T-80:
> ``Bus 001 Device 005: ID 24c6:5b00 Thrustmaster Ferrari 458 Racing Wheel``
> (It's t-80 f458 version but drivers are the same I'm pretty sure).
> 
> 

The drivers don't mater. What matters is how the device presents itself to the computer and in this case it identifies as a different device.

I'll add this one too.

**Comment by mmarusiak** [comment]
Great, I'll let you know if it detects the wheel then.

**Comment by berarma** [comment]
> Great, I'll let you know if it detects the wheel then.

Added.

**Comment by heater19** [comment]
was looking into why oversteer could not find the matplotlib package and I think it has to do with the following WARNING messages that pop up when I do the 'meson build' command:

The Meson build system
Version: 0.61.2
Source dir: /home/f81linux/Downloads/oversteer
Build dir: /home/f81linux/Downloads/oversteer/build
Build type: native build
Project name: oversteer
Project version: 0.7.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
**WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.**
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Configuring org.berarma.Oversteer.desktop.tmp using configuration
Program appstream-util found: YES (/usr/bin/appstream-util)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Configuring oversteer using configuration
Build targets in project: 14
NOTICE: Future-deprecated features used:
 * 0.55.0: {'ExternalProgram.path'}
 * 0.56.0: {'meson.build_root'}

Found ninja-1.10.1 at /usr/bin/ninja

---------------------------------------------------------------------------

what does 'setting "python.platlibdir" option' and "python.purelibdir" option' mean?
is it something I would add to the build command or does it mean in the code?

**Comment by berarma** [comment]
> was looking into why oversteer could not find the matplotlib package and I think it has to do with the following WARNING messages that pop up when I do the 'meson build' command:
> 
> The Meson build system Version: 0.61.2 Source dir: /home/f81linux/Downloads/oversteer Build dir: /home/f81linux/Downloads/oversteer/build Build type: native build Project name: oversteer Project version: 0.7.2 Host machine cpu family: x86_64 Host machine cpu: x86_64 Program python3 found: YES (/usr/bin/python3) **WARNING: Python files installed by Meson might not be found by python interpreter. This warning can be avoided by setting "python.platlibdir" option. WARNING: Python files installed by Meson might not be found by python interpreter. This warning can be avoided by setting "python.purelibdir" option.** WARNING: You should add the boolean check kwarg to the run_command call. It currently defaults to false, but it will default to true in future releases of meson. See also: [mesonbuild/meson#9300](https://github.com/mesonbuild/meson/issues/9300) Configuring org.berarma.Oversteer.desktop.tmp using configuration Program appstream-util found: YES (/usr/bin/appstream-util) Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate) Configuring oversteer using configuration Build targets in project: 14 NOTICE: Future-deprecated features used:
> 
>     * 0.55.0: {'ExternalProgram.path'}
> 
>     * 0.56.0: {'meson.build_root'}
> 
> 
> Found ninja-1.10.1 at /usr/bin/ninja
> 
> what does 'setting "python.platlibdir" option' and "python.purelibdir" option' mean? is it something I would add to the build command or does it mean in the code?

I've fixed some Meson deprecations. The warnings can be ignored. Try installing it and see where it gets installed and whether it works.

**Comment by berarma** [comment]
I think I've fixed the other warnings . They were probably harmless but the installation prefix was /usr instead of /usr/local. It should now always install in /usr/local by default.

**Comment by heater19** [comment]
progress has been made, the gui opens up and the Device shows the Thrustmaster T80 is being detected...however;

none of the buttons register;
turning the wheel or depressing the pedals does not show response;
the hat button do register, funny enough!

while running a game, there doesn't seem to be any input coming in from turning the wheel or using the pedals but the button do work;

**Comment by berarma** [comment]
> progress has been made, the gui opens up and the Device shows the Thrustmaster T80 is being detected...however;
> 
> none of the buttons register;
> turning the wheel or depressing the pedals does not show response;
> the hat button do register, funny enough!
> 
> while running a game, there doesn't seem to be any input coming in from turning the wheel or using the pedals but the button do work;

You can use evdev to find the event names generated when operating the wheel. If you send me a list I can make Oversteer recognize them. It won't help with the games though.

**Comment by heater19** [comment]
oh no, i didn't realize I would have to code things myself!  anyway, learned something new about the evdev;

here is the output from all the buttons on the wheel, however, turning the wheel and using the pedals did not generate any events, which is the real disappointing part since I just used the wheel on a windows machine and it was working fine --

device /dev/input/event26, name "Thrustmaster Thrustmaster T80", phys "usb-0000:00:14.0-2/input0"
event at 1690601246.181588, code 04, type 04, val 589830
key event at 1690601246.181588, 309 (BTN_Z), down
synchronization event at 1690601246.181588, SYN_REPORT 
event at 1690601246.381603, code 04, type 04, val 589830
key event at 1690601246.381603, 309 (BTN_Z), up
synchronization event at 1690601246.381603, SYN_REPORT 
event at 1690601308.152731, code 04, type 04, val 589830
key event at 1690601308.152731, 309 (BTN_Z), down
synchronization event at 1690601308.152731, SYN_REPORT 
event at 1690601308.280754, code 04, type 04, val 589830
key event at 1690601308.280754, 309 (BTN_Z), up
synchronization event at 1690601308.280754, SYN_REPORT 
event at 1690601313.012662, code 04, type 04, val 589828
key event at 1690601313.012662, 307 (['BTN_NORTH', 'BTN_X']), down
synchronization event at 1690601313.012662, SYN_REPORT 
event at 1690601313.180659, code 04, type 04, val 589828
key event at 1690601313.180659, 307 (['BTN_NORTH', 'BTN_X']), up
synchronization event at 1690601313.180659, SYN_REPORT 
event at 1690601314.880635, code 04, type 04, val 589825
key event at 1690601314.880635, 304 (['BTN_A', 'BTN_GAMEPAD', 'BTN_SOUTH']), down
synchronization event at 1690601314.880635, SYN_REPORT 
event at 1690601315.040675, code 04, type 04, val 589825
key event at 1690601315.040675, 304 (['BTN_A', 'BTN_GAMEPAD', 'BTN_SOUTH']), up
synchronization event at 1690601315.040675, SYN_REPORT 
event at 1690601316.352637, code 04, type 04, val 589827
key event at 1690601316.352637, 306 (BTN_C), down
synchronization event at 1690601316.352637, SYN_REPORT 
event at 1690601316.532615, code 04, type 04, val 589827
key event at 1690601316.532615, 306 (BTN_C), up
synchronization event at 1690601316.532615, SYN_REPORT 
event at 1690601317.720618, code 04, type 04, val 589826
key event at 1690601317.720618, 305 (['BTN_B', 'BTN_EAST']), down
synchronization event at 1690601317.720618, SYN_REPORT 
event at 1690601317.852564, code 04, type 04, val 589826
key event at 1690601317.852564, 305 (['BTN_B', 'BTN_EAST']), up
synchronization event at 1690601317.852564, SYN_REPORT 
event at 1690601320.852573, code 04, type 04, val 589831
key event at 1690601320.852573, 310 (BTN_TL), down
absolute axis event at 1690601320.852573, ABS_RX 
synchronization event at 1690601320.852573, SYN_REPORT 
event at 1690601320.952573, code 04, type 04, val 589831
key event at 1690601320.952573, 310 (BTN_TL), up
absolute axis event at 1690601320.952573, ABS_RX 
synchronization event at 1690601320.952573, SYN_REPORT 
event at 1690601327.112457, code 04, type 04, val 589832
key event at 1690601327.112457, 311 (BTN_TR), down
absolute axis event at 1690601327.112457, ABS_RY 
synchronization event at 1690601327.112457, SYN_REPORT 
event at 1690601327.240467, code 04, type 04, val 589832
key event at 1690601327.240467, 311 (BTN_TR), up
absolute axis event at 1690601327.240467, ABS_RY 
synchronization event at 1690601327.240467, SYN_REPORT 
event at 1690601330.032449, code 04, type 04, val 589835
key event at 1690601330.032449, 314 (BTN_SELECT), down
synchronization event at 1690601330.032449, SYN_REPORT 
event at 1690601330.172419, code 04, type 04, val 589835
key event at 1690601330.172419, 314 (BTN_SELECT), up
synchronization event at 1690601330.172419, SYN_REPORT 
event at 1690601331.240431, code 04, type 04, val 589836
key event at 1690601331.240431, 315 (BTN_START), down
synchronization event at 1690601331.240431, SYN_REPORT 
event at 1690601331.380443, code 04, type 04, val 589836
key event at 1690601331.380443, 315 (BTN_START), up
synchronization event at 1690601331.380443, SYN_REPORT 
event at 1690601335.652350, code 04, type 04, val 589837
key event at 1690601335.652350, 316 (BTN_MODE), down
synchronization event at 1690601335.652350, SYN_REPORT 
event at 1690601335.792350, code 04, type 04, val 589837
key event at 1690601335.792350, 316 (BTN_MODE), up
synchronization event at 1690601335.792350, SYN_REPORT 
absolute axis event at 1690601350.232166, ABS_HAT0Y 
synchronization event at 1690601350.232166, SYN_REPORT 
absolute axis event at 1690601350.460147, ABS_HAT0Y 
synchronization event at 1690601350.460147, SYN_REPORT 
absolute axis event at 1690601352.640127, ABS_HAT0X 
synchronization event at 1690601352.640127, SYN_REPORT 
absolute axis event at 1690601352.752109, ABS_HAT0X 
synchronization event at 1690601352.752109, SYN_REPORT 
absolute axis event at 1690601354.060103, ABS_HAT0X 
synchronization event at 1690601354.060103, SYN_REPORT 
absolute axis event at 1690601354.200092, ABS_HAT0X 
synchronization event at 1690601354.200092, SYN_REPORT 
absolute axis event at 1690601356.492079, ABS_HAT0Y 
synchronization event at 1690601356.492079, SYN_REPORT 
absolute axis event at 1690601356.612073, ABS_HAT0Y 
synchronization event at 1690601356.612073, SYN_REPORT 
event at 1690601360.120032, code 04, type 04, val 589834
key event at 1690601360.120032, 313 (BTN_TR2), down
synchronization event at 1690601360.120032, SYN_REPORT 
event at 1690601360.440029, code 04, type 04, val 589834
key event at 1690601360.440029, 313 (BTN_TR2), up
synchronization event at 1690601360.440029, SYN_REPORT 
event at 1690601367.531926, code 04, type 04, val 589833
key event at 1690601367.531926, 312 (BTN_TL2), down
synchronization event at 1690601367.531926, SYN_REPORT 
event at 1690601367.931925, code 04, type 04, val 589833
key event at 1690601367.931925, 312 (BTN_TL2), up
synchronization event at 1690601367.931925, SYN_REPORT 
event at 1690601576.685048, code 04, type 04, val 589830
key event at 1690601576.685048, 309 (BTN_Z), down
synchronization event at 1690601576.685048, SYN_REPORT 
event at 1690601576.913021, code 04, type 04, val 589830
key event at 1690601576.913021, 309 (BTN_Z), up
synchronization event at 1690601576.913021, SYN_REPORT 
event at 1690601577.792962, code 04, type 04, val 589829
key event at 1690601577.792962, 308 (['BTN_WEST', 'BTN_Y']), down
synchronization event at 1690601577.792962, SYN_REPORT 
event at 1690601578.072958, code 04, type 04, val 589829
key event at 1690601578.072958, 308 (['BTN_WEST', 'BTN_Y']), up
synchronization event at 1690601578.072958, SYN_REPORT 
event at 1690601581.532970, code 04, type 04, val 589828
key event at 1690601581.532970, 307 (['BTN_NORTH', 'BTN_X']), down
synchronization event at 1690601581.532970, SYN_REPORT 
event at 1690601581.764947, code 04, type 04, val 589828
key event at 1690601581.764947, 307 (['BTN_NORTH', 'BTN_X']), up
synchronization event at 1690601581.764947, SYN_REPORT 
event at 1690601582.212926, code 04, type 04, val 589827
key event at 1690601582.212926, 306 (BTN_C), down
synchronization event at 1690601582.212926, SYN_REPORT 
event at 1690601582.444909, code 04, type 04, val 589827
key event at 1690601582.444909, 306 (BTN_C), up
synchronization event at 1690601582.444909, SYN_REPORT 
event at 1690601582.912934, code 04, type 04, val 589825
key event at 1690601582.912934, 304 (['BTN_A', 'BTN_GAMEPAD', 'BTN_SOUTH']), down
synchronization event at 1690601582.912934, SYN_REPORT 
event at 1690601583.112938, code 04, type 04, val 589825
key event at 1690601583.112938, 304 (['BTN_A', 'BTN_GAMEPAD', 'BTN_SOUTH']), up
synchronization event at 1690601583.112938, SYN_REPORT 
event at 1690601583.472933, code 04, type 04, val 589826
key event at 1690601583.472933, 305 (['BTN_B', 'BTN_EAST']), down
synchronization event at 1690601583.472933, SYN_REPORT 
event at 1690601583.704897, code 04, type 04, val 589826
key event at 1690601583.704897, 305 (['BTN_B', 'BTN_EAST']), up
synchronization event at 1690601583.704897, SYN_REPORT 
event at 1690601586.244864, code 04, type 04, val 589835
key event at 1690601586.244864, 314 (BTN_SELECT), down
synchronization event at 1690601586.244864, SYN_REPORT 
event at 1690601586.392892, code 04, type 04, val 589835
key event at 1690601586.392892, 314 (BTN_SELECT), up
synchronization event at 1690601586.392892, SYN_REPORT 
event at 1690601586.884882, code 04, type 04, val 589836
key event at 1690601586.884882, 315 (BTN_START), down
synchronization event at 1690601586.884882, SYN_REPORT 
event at 1690601587.124840, code 04, type 04, val 589836
key event at 1690601587.124840, 315 (BTN_START), up
synchronization event at 1690601587.124840, SYN_REPORT 
event at 1690601587.572847, code 04, type 04, val 589831
key event at 1690601587.572847, 310 (BTN_TL), down
absolute axis event at 1690601587.572847, ABS_RX 
synchronization event at 1690601587.572847, SYN_REPORT 
event at 1690601587.792854, code 04, type 04, val 589831
key event at 1690601587.792854, 310 (BTN_TL), up
absolute axis event at 1690601587.792854, ABS_RX 
synchronization event at 1690601587.792854, SYN_REPORT 
event at 1690601588.284852, code 04, type 04, val 589832
key event at 1690601588.284852, 311 (BTN_TR), down
absolute axis event at 1690601588.284852, ABS_RY 
synchronization event at 1690601588.284852, SYN_REPORT 
event at 1690601588.492809, code 04, type 04, val 589832
key event at 1690601588.492809, 311 (BTN_TR), up
absolute axis event at 1690601588.492809, ABS_RY 
synchronization event at 1690601588.492809, SYN_REPORT 
event at 1690601591.804829, code 04, type 04, val 589834
key event at 1690601591.804829, 313 (BTN_TR2), down
synchronization event at 1690601591.804829, SYN_REPORT 
event at 1690601592.324813, code 04, type 04, val 589834
key event at 1690601592.324813, 313 (BTN_TR2), up
synchronization event at 1690601592.324813, SYN_REPORT 
event at 1690601594.452754, code 04, type 04, val 589833
key event at 1690601594.452754, 312 (BTN_TL2), down
synchronization event at 1690601594.452754, SYN_REPORT 
event at 1690601594.932718, code 04, type 04, val 589833
key event at 1690601594.932718, 312 (BTN_TL2), up
synchronization event at 1690601594.932718, SYN_REPORT 
absolute axis event at 1690601596.732712, ABS_HAT0Y 
synchronization event at 1690601596.732712, SYN_REPORT 
absolute axis event at 1690601597.004725, ABS_HAT0Y 
synchronization event at 1690601597.004725, SYN_REPORT 
absolute axis event at 1690601597.504674, ABS_HAT0Y 
synchronization event at 1690601597.504674, SYN_REPORT 
absolute axis event at 1690601597.772712, ABS_HAT0Y 
synchronization event at 1690601597.772712, SYN_REPORT 
absolute axis event at 1690601598.384715, ABS_HAT0X 
synchronization event at 1690601598.384715, SYN_REPORT 
absolute axis event at 1690601598.752662, ABS_HAT0X 
synchronization event at 1690601598.752662, SYN_REPORT 
absolute axis event at 1690601599.272662, ABS_HAT0X 
synchronization event at 1690601599.272662, SYN_REPORT 
absolute axis event at 1690601599.504682, ABS_HAT0X 
synchronization event at 1690601599.504682, SYN_REPORT 
absolute axis event at 1690601600.304709, ABS_HAT0X 
synchronization event at 1690601600.304709, SYN_REPORT 
absolute axis event at 1690601600.692684, ABS_HAT0X 
synchronization event at 1690601600.692684, SYN_REPORT 
absolute axis event at 1690601601.224654, ABS_HAT0Y 
synchronization event at 1690601601.224654, SYN_REPORT 
absolute axis event at 1690601601.552658, ABS_HAT0Y 
synchronization event at 1690601601.552658, SYN_REPORT 
absolute axis event at 1690601602.332645, ABS_HAT0Y 
synchronization event at 1690601602.332645, SYN_REPORT 
absolute axis event at 1690601602.524634, ABS_HAT0Y 
synchronization event at 1690601602.524634, SYN_REPORT

**Comment by berarma** [comment]
> oh no, i didn't realize I would have to code things myself! anyway, learned something new about the evdev;

You're not coding anything but it would help me tremendously if you did. This isn't something that I do for a pay.

> here is the output from all the buttons on the wheel, however, turning the wheel and using the pedals did not generate any events, which is the real disappointing part since I just used the wheel on a windows machine and it was working fine

I see ABS_HAT0X and ABS_HAT0Y that I guess correspond to the HAT.

Then there's ABS_RX and ABS_RY. What's what?

The pedals might be seen as another device to the computer. It's not usual but it could be. Do you see some other device in the list that could be the pedals?

You might want to contact the authors of the T150 and T300 drivers (see the README). Their knowledge of Thrustmaster wheels might help.

**Comment by heater19** [comment]
no worries, I was joking; definitely appreciate your help in getting this wheel to work;

this is what I came up with (copying straight from the evdev help page) to get a list of devices --------
`import evdev

devices = [evdev.InputDevice(path) for path in evdev.list_devices()]

for device in devices:
     print(device.path, device.name, device.phys)`

and the only terminal output is:
`/dev/input/event3 Thrustmaster Thrustmaster T80 usb-0000:00:14.0-2/input0`

since you pointed out the ABS_RX and ABS_RY, I went back on the evdev help page and to my understanding, it's the absolute axis that is supposed to be linked to the wheel and the pedals;  but in this situation the absolute axis events are being triggered by the buttons instead; specifically:
BTN_TL and BTN_TR on the wheel also trigger the ABS_RX and ABS_RY events;
and the hat input is also being seen as an absolute axis

I will look into what is happening with the T150 and T300;

thanks again;

**Comment by berarma** [comment]
Running `evdev` outputs a list of devices. There's no other device that could be the pedals?

**Comment by heater19** [comment]
that's the only output i see, unless there's another way of checking

**Comment by berarma** [comment]
Sorry, the command is `evtest`. My bad.

**Comment by heater19** [comment]
this is the output from the evtest command:

```
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event3:	Thrustmaster Thrustmaster T80
Select the device event number [0-3]:
```

**Comment by berarma** [comment]
If the pedals don't generate events for any device then I can't read their state. Sorry. You might find more help in the Thrustmaster driver projects. If you figure it out please contact me.

**Comment by heater19** [comment]
I think you're right;
will try and see if I can get it added to their driver project;
thank you for your help;

**Comment by seamuseats** [comment]
running evtest I don't see any input that may correspond to the wheel or pedals. Everything else works though. Functions correctly on Windows. Is this something still in the works, if not, is there a known fix?

**Comment by seamuseats** [comment]
switching the wheel to PS3 mode, evtest recognizes the input

**Comment by berarma** [comment]
> running evtest I don't see any input that may correspond to the wheel or pedals. Everything else works though. Functions correctly on Windows. Is this something still in the works, if not, is there a known fix?

This is an issue tracker for Oversteer. Please, if you have an issue using this software open a new issue. Don't post on an old and closed issue.
