### ISSUE TITLE
udev rules need to be fixed

### ISSUE THREAD

**Issue by alxwk** [berarma/oversteer#146]
Not to be rude, but udev rules are a mess. The path to set permissions is wrong, and any rule works only because it fires **multiple** times (due to "wildcard" keys like SUBSYSTEM**S** or DRIVER**S** instead of SUBSYSTEM or DRIVER), and in one or two of these times the path happens to match. To see what I'm talking about, try to add some debug output like, say, `echo ACTION:%E{ACTION} SUBSYSTEM:%E{SUBSYSTEM} DRIVER:%E{DRIVER} PATH:%p >> /tmp/ruletest` to any of them. For example, when I do this in the rule for my DFGT, I get the following in `/tmp/ruletest`:
```
ACTION:add SUBSYSTEM:hid DRIVER:logitech PATH:/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C
ACTION:add SUBSYSTEM:hidraw DRIVER: PATH:/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C/hidraw/hidraw5
ACTION:add SUBSYSTEM:input DRIVER: PATH:/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C/input/input123
ACTION:add SUBSYSTEM:input DRIVER: PATH:/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C/input/input123/js0
ACTION:add SUBSYSTEM:input DRIVER: PATH:/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C/input/input123/event19
ACTION:bind SUBSYSTEM:hid DRIVER:logitech PATH:/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C
```
The path `/devices/pci0000:00/0000:00:02.1/0000:02:00.0/0000:03:0c.0/0000:0d:00.0/usb3/3-5/3-5:1.0/0003:046D:C29A.006C` is the one where control files are, which permissions need to be set. As one can see, the path `%S%p/../../../` which is used in the rules, matches the real one in `js0` and `event19` cases, in others the rule just fails silently.

The following patch adds "add" action to the keys, changes all wildcard keys to specific ones, and fixes paths. It's only for Logitech rules though, I didn't look into others, but the situation there is probably the same.

[udev_patch.txt](https://github.com/berarma/oversteer/files/12249662/udev_patch.txt) (I don't know why github doesn't allow me to upload a patch with .patch extension)

**Comment by berarma** [comment]
I think I copied this from a Feral rules file made for their games. I made some changes to it and never gave it much thought.

About attaching patches, I guess GH expects you to make a pull request instead.

Everything you propose seems to be right. And what do you think about the KERNEL matching? Would it be better using this instead for more precise matching?

```
ATTRS{idVendor}=="046d"
ATTRS{idProduct}=="c29a"
```
