### ISSUE TITLE
how to use force feedback such as autocenter with Fanatec devices?

### ISSUE THREAD

**Issue by yhg8423** [berarma/oversteer#151]
Hi, thank you for maintaining the oversteer repository.

I am currently using a Fanatec device and I want to use oversteer for giving force feedback (especially autocenter) to Fanatec wheel base.

However, the force feedback gain range in oversteer is disable when using a Fantec device. Therefore, I checked the 99-fanatec-wheel-perms.rules and found that there is only 'chmod 666 range display leds/*/brightness' in the rule. Thus, I added 'autocenter' but it still did not work.

Is there any way to enable force feedback for Fanatec devices?

**Comment by berarma** [comment]
You will need a module driver for your Fanatec wheel. There are two methods to set autocenter and the driver has to support one of them. Which driver and wheel are you using?

**Comment by yhg8423** [comment]
Thank you for answer. I am using FANATEC Podium Wheel Base DD2 for wheel and hid-[fanatecff ](https://github.com/gotzl/hid-fanatecff) for driver!

**Comment by berarma** [comment]
You should open an issue in that project asking to support the autocenter effect.
