### ISSUE TITLE
Wrong Udev rules location for distros using eUdev. Results in : You don't have the required permission to change your wheel settings

### ISSUE THREAD

**Issue by JJones780** [berarma/oversteer#155]
udev admin rules are not being installed to proper directory for Debian based systems.
Results in the error:  **you don't have the required permission to change your wheel settings**  when running Oversteer.

I'm running Devuan ( and it appears to be true for other Debian-based installations).
When I run 
`udevadm test /devices/pci0000:00/0000:00:02.1/0000:02:00.0/usb1/1-5/1-5:1.0/0003:046D:C29C.001F/input/input118`
( where the path is found by looking at `sudo dmesg` )
I don't see it scanning ` /lib/local/udev/rules.d ` 

`man udev `  on my system mentions  /lib/ and /usr/lib prefixes ( as well as /etc and /run ) but makes no mention of /usr/local/udev/rules.d  although I see it mentioned in other udev man pages found online.

This [StackExchange page](https://unix.stackexchange.com/questions/732279/does-the-location-of-package-installed-udev-rules-differ-across-linux-distributi) investigates the question.

**Comment by berarma** [comment]
When using master, the rules would be installed by default in /usr/local/lib/udev/rules.d.

You can change that locaton with option udev_rules_dir when running meson.

Where is it installing the rules?

Are you using the latest master?

**Comment by JJones780** [comment]
Yes it installed to /usr/local/lib/udev/rules.d but the problem is that Debian ( or at least Devuan ) doesn't look there.
I've got it working fine. Thanks for your great work.

I'll do a bit more research on the best way to decide on  /usr/local  vs  /usr  for  lib/udev/rules.d  with regard to meson installing oversteer and see if I can suggest a good solution for you to consider in order to avoid others experiencing this issue.

**Comment by JJones780** [comment]
Debian [Buster Udev manpage](https://manpages.debian.org/buster/udev/udev.7.en.html) doesn't list /usr/local/lib/udev/rules.d but the next version, [Bullseye udev manpage](https://manpages.debian.org/bullseye/udev/udev.7.en.html) does.
/usr/local/ is meant for self-compiled libraries etc so it kinda makes sense to use it and maybe the udev rules there will become standard across all distributions soon.
 Oh ok, wow.. this is my first gotcha related to not running systemd on this machine ( just being stubborn ;) . I guess udev has been subsumed into systemd and non-systemd distros use eudev which hasn't made this change yet.
I'll open an issue on eudev.
Do whatever you feel is best here... nothing required but it might be nice to make a brief note in the readme?
Thanks again for your work on Oversteer.

**Comment by JJones780** [comment]
eudev was quick to [make the fix](https://github.com/eudev-project/eudev/commit/298ef249e3b6015f34de7c3c7df9bf68e2fe56b6)! Distros using eudev shouldn't experience this problem once this makes its way to them.  

In the meantime if anyone has the permission error an easy way I found to see if udev is checking their rule is to run `udevadm test abc`.

**Comment by berarma** [comment]
I think it isn't worth filling the README even more, it's well documented here. And soon it won't be an issue anymore.

Thanks for clearing this up and helping fixing the issue at the root.
