### ISSUE TITLE
error in install description

### ISSUE THREAD

**Issue by byteswap-rpog** [berarma/oversteer#158]
I had some issues following the installation guide and ended up with some errors. After all, it seems that only a small error in the description was the issue.

in:
"apt install python3 python3-distutils python3-gi python-gi-cairo python3-pyudev python3-xdg python3-evdev gettext meson appstream-util desktop-file-utils python3-matplotlib python3-scipy"

there should be "python3-gi-cairo" instead of "python-gi-cairo".

please check and modify the description. Thanks!

**Comment by berarma** [comment]
Thanks!
