### ISSUE TITLE
G920 not recognized

### ISSUE THREAD

**Issue by Hedronmx** [berarma/oversteer#16]
Hello! I know this might not be the best place but i really dont know where to ask for help.

I cant make usb_modeswitch to automatically switch the wheel's mode. I can make it work by running
`sudo usb_modeswitch -c /etc/usb_modeswitch.d/046d:c261`

But i would love this to be automatically. I have created the udev and the modeswitch rule for the wheel but it wont do it automatically.

If you know a better place to ask for help, please let me know.

Thank you!

**Comment by berarma** [comment]
Right, this is not the place. I'd try using the full path to the usb_modeswitch command in the udev rule and make sure the device id is right, but if that doesn't work you should ask in the support forums for your distro. Even if they don't have the same device they might know what is wrong in the way you set up udev.

**Comment by Hedronmx** [comment]
Alright! Thanks for your time! ill give it a shot
