### ISSUE TITLE
Wrong version number in meson.build

### ISSUE THREAD

**Issue by dbro86** [berarma/oversteer#164]
You tagged the new version as 0.8.0 but the version number in meson.build is still 0.7.3

**Comment by berarma** [comment]
Ugh, sorry. I hesitated between 0.7.3 and 0.8 and forgot to change it.

**Comment by berarma** [comment]
I've left the current release as is with adding a note to avoid any confusion. As soon as there's some other fix I'll make a new release with the version number changed.

Thanks.
