### ISSUE TITLE
Oversteer won't start

### ISSUE THREAD

**Issue by bigmane** [berarma/oversteer#165]
I'm on arch, using KDE, i installed oversteer from github and i have a Thrustmaster T248.

So as the title says my problem is that the application won't start, it only has the little icon as it is going to start but it won't start and after a few seconds the icon goes away without the application starting.

I'am a little bit a of a newbie to linux so sorry if some of my explanations are nonsense to anyone who knows what they're talking about and if any logs are needed to help me i'd be happy to oblige you if i just get instructions on how to get those logs, thanks in advance.

**Comment by berarma** [comment]
Start a terminal, type `oversteer` and intro. It will start the app and show errors in the terminal.

Type `oversteer --debug` instead and it will show additional debug info. Paste this output here and it should be enough.

**Comment by bigmane** [comment]
When typing in just oversteer i get:
└─$ oversteer
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 48, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
                                                                                                                               

And when typing in oversteer ---debug:
└─$ oversteer --debug                                                                                                    130 ⨯
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 48, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
                                                                          

Hope this helps and this also gives me some ideas so i will be looking into stuff on a little on my own and if i fix this i will add a comment saying so.

**Comment by berarma** [comment]
This is usually caused by a bad locale setting.

Command `locale -a` in the terminal show all locale settings. You should use valid locale definitions.

**Comment by bigmane** [comment]
which one these seems to be the problem to you? (sorry if this seems dumb as i said im a relative newbie to this.)

└─$ locale -a                                                                                                              1 ⨯
C
C.utf8
en_US.utf8
POSIX

**Comment by berarma** [comment]
Sorry, I explained badly. Those are the generated locales in your system.

To see the locales in use just type: `locale`

**Comment by bigmane** [comment]
Ok, heres the output when i run just the locale command alone.

└─$ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_FI.UTF-8
LC_TIME=en_FI.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_FI.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=en_FI.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by berarma** [comment]
The local en_FI is invalid because it isn't defined in your system. The first command listed the available locales.

There will be some command to reconfigure your locales depending on your distro.

**Comment by fily-gif** [comment]
sorry for deadposting(?), but i have the same error, locale output:

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
``` 
im using arch btw

**Comment by berarma** [comment]
Please, ask in your distro's help forums. This is an issue with your installation.
