### ISSUE TITLE
"You don't have the required permissions to change your wheel settings" G923 - Arch

### ISSUE THREAD

**Issue by MochaDF** [berarma/oversteer#166]
I'm getting this error trying to use my G923 with oversteer.

Ouput of oversteer --debug
`➜  ~ oversteer --debug
DEBUG:root:update_device_list: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010/input/input31/event25 /dev/input/event25
DEBUG:root:/dev/input/event25: ID_VENDOR_ID: 046d ID_MODEL_ID: c26e
DEBUG:root:Devices: {'/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010/input/input31/event25': <oversteer.device.Device object at 0x7f31fbe5f090>}
DEBUG:root:/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010/input/input31/event25: {'device_manager': <oversteer.device_manager.DeviceManager object at 0x7f31fb461090>, 'input_device': None, 'id': '/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010/input/input31/event25', 'vendor_id': '046d', 'product_id': 'c26e', 'usb_id': '046d:c26e', 'dev_path': '/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010', 'dev_name': '/dev/input/event25', 'name': 'Logitech G923 Racing Wheel for Xbox One and PC', 'ready': True, 'max_range': 900}
DEBUG:matplotlib:matplotlib data path: /usr/lib/python3.11/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/mocha/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/mocha/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/mocha/.cache/matplotlib/fontlist-v330.json
DEBUG:root:check_permissions: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010
DEBUG:root:check_file_permissions mode: 0o664 user: root group: root file: /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010/range
DEBUG:root:flush_device
DEBUG:root:Setting autocenter strength: 0
DEBUG:root:Setting FF gain: 65535
DEBUG:root:flush_ui`

Output of cat /proc/bus/input/devices

`I: Bus=0003 Vendor=046d Product=c26e Version=0111
N: Name="Logitech G923 Racing Wheel for Xbox One and PC"
P: Phys=usb-0000:09:00.3-5/input0
S: Sysfs=/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-5/5-5:1.0/0003:046D:C26E.0010/input/input31
U: Uniq=50-0f-3c-6d
H: Handlers=event25 js0 
B: PROP=0
B: EV=20001b
B: KEY=7f 0 0 0 0 0 0 ffff00000000 0 0 0 0
B: ABS=30027
B: MSC=10
B: FF=31f2f0000 0`

**Comment by berarma** [comment]
Have you installed Oversteer following the instructions then restarted your computer?

The udev rules files should be installed and working.

**Comment by MochaDF** [comment]
Yeah I installed Oversteer then restarted my PC. Oversteer didn't detect my wheel at first though so i had to use usb-modeswitch and run this command `usb_modeswitch -v 046d -p c26d -M 0f00010142 -C 0x03 -m 01 -r 01`

here is the entry for my wheel in the udev file 
![image](https://github.com/berarma/oversteer/assets/37279329/fb093c7d-6d8b-4f1f-ba49-4215fd9ec6b0)

**Comment by berarma** [comment]
Do you have FFB? Your kernel should be new enough to support your wheel. Which kernel version are you using?

**Comment by MochaDF** [comment]
6.5.9-zen2-1-zen

**Comment by berarma** [comment]
Does the FFB work?

**Comment by MochaDF** [comment]
in BeamNG I don't get any vibrations and if I pause the wheel will randomly go full lock in either direction

**Comment by MochaDF** [comment]
I plugged my wheel into a USB 3 port on the back of my PC instead of the front I/O and now I can feel some vibration, but it's not as strong as when I play on windows

**Comment by berarma** [comment]
Could you try debug the udev rules?

After running the usb_modeswitch command there should be an udev event that triggered the rule for your wheel.

**Comment by MochaDF** [comment]
not exactly sure if I did what you asked. Is this what you're asking for?

`Nov 05 14:48:27 archmochadesktop kernel: usb 5-2.1: SerialNumber: 00006e836d3c61d3
Nov 05 14:48:27 archmochadesktop kernel: input: Logitech G923 Racing Wheel for Xbox One and PC as /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-2/5-2.1/5-2.1:1.0/0003:046D:C26E.0012/input/input32
Nov 05 14:48:27 archmochadesktop kernel: logitech-hidpp-device 0003:046D:C26E.0012: input,hiddev106,hidraw13: USB HID v1.11 Joystick [Logitech G923 Racing Wheel for Xbox One and PC] on usb-0000:09:00.3-2.1/input0
Nov 05 14:48:27 archmochadesktop kernel: logitech-hidpp-device 0003:046D:C26E.0012: HID++ 4.2 device connected.
Nov 05 14:48:27 archmochadesktop kernel: logitech-hidpp-device 0003:046D:C26E.0012: Force feedback support loaded (firmware release 2).
Nov 05 14:48:27 archmochadesktop kernel: logitech-hidpp-device 0003:046D:C26E.0013: hiddev107,hidraw14: USB HID v1.11 Device [Logitech G923 Racing Wheel for Xbox One and PC] on usb-0000:09:00.3-2.1/input1
Nov 05 14:48:27 archmochadesktop mtp-probe[42334]: checking bus 5, device 9: "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-2/5-2.1"
Nov 05 14:48:27 archmochadesktop mtp-probe[42334]: bus: 5, device: 9 was not an MTP device
Nov 05 14:48:27 archmochadesktop mtp-probe[42356]: checking bus 5, device 9: "/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:09:00.3/usb5/5-2/5-2.1"
Nov 05 14:48:27 archmochadesktop mtp-probe[42356]: bus: 5, device: 9 was not an MTP device`

**Comment by MochaDF** [comment]
![image](https://github.com/berarma/oversteer/assets/37279329/89a3521e-18db-4651-8ca1-4589e132214f)
 I am able to run a test in Oversteer

**Comment by BlizzieM** [comment]
I'm getting same issue on EndeavorOS with G29. I tried to reinstall software with udevs reinstalled but for no luck. Here's what debug printout says:

`[blizziem@IronMare ~]$ oversteer --debug
DEBUG:root:update_device_list: /devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001/input/input22/event20 /dev/input/event20
DEBUG:root:/dev/input/event20: ID_VENDOR_ID: 046d ID_MODEL_ID: c24f
DEBUG:root:Devices: {'/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001/input/input22/event20': <oversteer.device.Device object at 0x7f6393569550>}
DEBUG:root:/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001/input/input22/event20: {'device_manager': <oversteer.device_manager.DeviceManager object at 0x7f6393eaf250>, 'input_device': None, 'id': '/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001/input/input22/event20', 'vendor_id': '046d', 'product_id': 'c24f', 'usb_id': '046d:c24f', 'dev_path': '/sys/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001', 'dev_name': '/dev/input/event20', 'name': 'Logitech G29 Driving Force Racing Wheel', 'ready': True, 'max_range': 900}
DEBUG:matplotlib:matplotlib data path: /usr/lib/python3.11/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/blizziem/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/blizziem/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/blizziem/.cache/matplotlib/fontlist-v330.json
DEBUG:root:check_permissions: /sys/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001
DEBUG:root:check_file_permissions mode: 0o664 user: root group: root file: /sys/devices/pci0000:00/0000:00:01.2/0000:01:00.0/0000:02:08.0/0000:06:00.3/usb3/3-1/3-1:1.0/0003:046D:C24F.0001/alternate_modes
`
I'm on 6.6.7-arch1-1 kernel.

**Comment by berarma** [comment]
It looks like your distro isn't finding the udev files. See #155.

You can try copying the files manually to the directory `/etc/udev/rules.d` where I think they should be found.

Meson can be given the option `udev_rules_dir` to change the directory where this files are installed instead of copying them by hand.

Check with your distro's help forums for more info.

**Comment by Doaner** [comment]
I am currently having the same issue on Fedora 39 with my G920. Force feedback works, but it is weak and becomes very delayed in games with heavy CPU usage, such as BeamNG with AI vehicles. Here my debug printout here:

DEBUG:root:update_device_list: /devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001/input/input13/event10 /dev/input/event10
DEBUG:root:/dev/input/event10: ID_VENDOR_ID: 046d ID_MODEL_ID: c262
DEBUG:root:Devices: {'/devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001/input/input13/event10': <oversteer.device.Device object at 0x7f4e86205d60>}
DEBUG:root:/devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001/input/input13/event10: {'device_manager': <oversteer.device_manager.DeviceManager object at 0x7f4e86334440>, 'input_device': None, 'id': '/devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001/input/input13/event10', 'vendor_id': '046d', 'product_id': 'c262', 'usb_id': '046d:c262', 'dev_path': '/sys/devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001', 'dev_name': '/dev/input/event10', 'name': 'Logitech G920 Driving Force Racing Wheel for Xbox One', 'ready': True, 'max_range': 900}
DEBUG:matplotlib:matplotlib data path: /usr/share/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/ndoane/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/ndoane/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/ndoane/.cache/matplotlib/fontlist-v330.json
DEBUG:root:check_permissions: /sys/devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001
DEBUG:root:check_file_permissions mode: 0o664 user: root group: root file: /sys/devices/pci0000:00/0000:00:08.1/0000:30:00.4/usb5/5-1/5-1:1.0/0003:046D:C262.0001/range

**Comment by ExpandingShapes** [comment]
Got the same issue on Endeavour. I was able to change settings after a reboot. However the was no such problem on Ubuntu

**Comment by berarma** [comment]
Have you tried [this](https://github.com/berarma/oversteer/issues/166#issuecomment-1863492728)?

Oversteer won't have any effect on the feedback. Wheels using the HID++ driver like all XBox/PC devices will experience FFB lag in some games due to the way the driver works. This issue has nothing to do with heavy CPU usage but the FFB update rate used by the game. So it might be something else in the game. I think BeamNG has been reported to have FFB issues.

I'll close this now so it doesn't get too long and unmanageable. Please, create new separate issues after trying the suggestions in this thread if the problems persists. FFB issues should be reported to the Proton tracker for games using Proton or their technical support for the native games.
