### ISSUE TITLE
please add Logitech Saitek Heavy Equipment Wheel

### ISSUE THREAD

**Issue by Ice-Wolve** [berarma/oversteer#167]
I just purchased an please add Logitech Saitek Heavy Equipment Wheel. I would like to see this setup supported.
I use Manjaro Linux.

Thanks

**Comment by berarma** [comment]
Sure. I see it has 900 degrees rotation. I also need the USB vendor/product id.

**Comment by berarma** [comment]
I though this issue was opened just now. Somehow it slipped under my radar. Sorry.
