### ISSUE TITLE
Can't build Oversteer in OpenSUSE

### ISSUE THREAD

**Issue by OakLD** [berarma/oversteer#171]
Hello,

I have trouble compiling the package in OpenSUSE. I followed the guide. Got some warnings when installing dependencies, but it looked unrelated to package installation.

`meson build`  results in:  

```
meson.build:16:61: ERROR: Command "/home/libor/Sys/Anaconda/bin/python3 -c import importlib.util; import sys; exit(1) if importlib.util.find_spec('gi') is None else exit(0)" failed with status 1.
```

Looks like result of line 15: `script = 'import importlib.util; import sys; exit(1) if importlib.util.find_spec(\''+ p +'\') is None else exit(0)'`. So it seems `gi` is not loaded, probably  not available. 

Trying to install `gi`, it fails:
```
(base) linux-e53g:/home/libor/Sys/Build/oversteer # pip3 install gi
ERROR: Could not find a version that satisfies the requirement gi (from versions: none)
ERROR: No matching distribution found for gi
```

I've read, that correct package name for `gi` is `pgi` and should be installed that way, it worked:
```
(base) linux-e53g:/home/libor/Sys/Build/oversteer # pip3 install pgi
Collecting pgi
  Downloading pgi-0.0.11.2.tar.gz (239 kB)
     |████████████████████████████████| 239 kB 1.4 MB/s 
Building wheels for collected packages: pgi
  Building wheel for pgi (setup.py) ... done
  Created wheel for pgi: filename=pgi-0.0.11.2-py3-none-any.whl size=181799 sha256=fbb8cdd74fed4cc6740e9369b1733857102f274d8c6440f45150111288dc6964
  Stored in directory: /root/.cache/pip/wheels/5a/86/d0/7de9cc3ab74eb6a7f9b0f6378f2b8863e731b5772e0cffe3c5
Successfully built pgi
Installing collected packages: pgi
Successfully installed pgi-0.0.11.2
```

But I get the same error about `gi` missing. I guess the package has been renamed, but is referred still as `gi`, in this project? Just my wild guess. 
Any help appreciated :-)

**Comment by OakLD** [comment]
OK, I've managed to find `oversteer-0.6.0-1.930.noarch.rpm` in the dark corners of OpenSUSE Build service.

**Comment by berarma** [comment]
Glad it's solved. I can't help much with issues related to custom Python installs.
