### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by deimantas3** [berarma/oversteer#177]
Installed oversteer using yay from AUR, rebooted system and then when trying to run the application through the shortcut nothing happens.

Trying to open it through terminal, or typing oversteer --help ends up with this error:

Traceback (most recent call last):
  File "/usr/bin/oversteer", line 48, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.11/locale.py", line 626, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting

not sure what to do

**Comment by berarma** [comment]
Please, search the multiple closed issues about the same error. I should put a link in the Readme.
