### ISSUE TITLE
Can't seem to uninstall.

### ISSUE THREAD

**Issue by MicHaeL-MonStaR** [berarma/oversteer#178]
It's probably my ignorance, but I can't seem to uninstall Oversteer (to update it after), because upon entering the commands from the instructions, it keeps saying "no such file or directory", either in the Home directory or Oversteer within that.

I suppose I don't understand where to navigate first. - Is the "project directory" not the Oversteer-folder that it's installed to?

**Comment by berarma** [comment]
You have to run `ninja uninstall` inside the build directory that is created when installing it.

Please, paste the command and the output here if it still doesn't work.

**Comment by MicHaeL-MonStaR** [comment]
I've opened the `build`-folder within the `oversteer`-folder that was made in the Home-directory (I believe), but this happens when running `ninja uninstall`. - Is this the wrong place perhaps?

![Screenshot from 2024-01-26 17-23-02](https://github.com/berarma/oversteer/assets/63430813/5377b2a3-ba61-4b55-a506-3f92205d4354)

**Comment by berarma** [comment]
> I've opened the `build`-folder within the `oversteer`-folder that was made in the Home-directory (I believe), but this happens when running `ninja uninstall`. - Is this the wrong place perhaps?
> 
> ![Screenshot from 2024-01-26 17-23-02](https://github.com/berarma/oversteer/assets/63430813/5377b2a3-ba61-4b55-a506-3f92205d4354)
> 

The `build` directory should be inside the Oversteer directory. It's created in the installation process.

**Comment by MicHaeL-MonStaR** [comment]
It is. Or is this not it?...
![Screenshot from 2024-01-27 20-24-06](https://github.com/berarma/oversteer/assets/63430813/64881b6a-09e4-4910-84b4-952bb08757fe)

**Comment by berarma** [comment]
If you follow the install instructions the `build.ninja` file should be inside the build directory.

You can try installing again the same version you have then run the uninstall command from that same build directory. It should work.
