### ISSUE TITLE
meson build warning

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [berarma/oversteer#180]
If i build with meson build the following output comes on Ubuntu-Mate 22.04LTS and Kernel Linux 6.5.0-15-generic x86_64.

git clone https://github.com/berarma/oversteer.git
~/oversteer$ meson build
"
The Meson build system
Version: 0.61.2
Source dir: /home/sascha/oversteer
Build dir: /home/sascha/oversteer/build
Build type: native build
Project name: oversteer
Project version: 0.8.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.platlibdir" option.
WARNING: Python files installed by Meson might not be found by python interpreter.
 This warning can be avoided by setting "python.purelibdir" option.
Configuring org.berarma.Oversteer.desktop.tmp using configuration
Program appstream-util found: YES (/usr/bin/appstream-util)
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Configuring oversteer using configuration
Build targets in project: 16

Found ninja-1.10.1 at /usr/bin/ninja
"

And if i install it with 

"cd build"
"sudo ninja install" 

they dosn't copy the udev-rules to the default directory.
And i have no rights to change Wheelsettings.

Please help
Greetings

**Comment by berarma** [comment]
Where are they copied? Do you reboot after installing?

**Comment by SaschaVasarrhelyi** [comment]
I copy myself the Files to
~$ sudo cp $HOME/oversteer/data/udev/*.* /etc/udev/rules.d
and
sudo cp $HOME/oversteer/data/udev/*.* /usr/local/lib/udev/rules.d

that dose the trick. Now Oversteer can change the Settings.

**Comment by SaschaVasarrhelyi** [comment]
After install there in no directory it must be in it.
not in all of the directorys they on readme bzw website of you declarated.
i have first used 
sudo udevadm control --reload-rules && sudo udevadm trigger

than i have rebootet and no change.
than i copied the files to the both directorys and plug my DFGT out and on and now its work correct.

**Comment by berarma** [comment]
Maybe the /usr/local/lib/udev directory didn't exist before you copied the files manually.

**Comment by SaschaVasarrhelyi** [comment]
Jes that's true.
