### ISSUE TITLE
Add support for input-remapper gamepad

### ISSUE THREAD

**Issue by kopach** [berarma/oversteer#182]
[Input remapper](https://github.com/sezanzeb/input-remapper/) is another great Linux tool which can remap any keys/gamepad buttons or even axis desired gamepad buttons/axis.
Using this tool, I can remap almost any pedals/racing wheel axis to generic "input remaper" GamePad axis.
It would be great for Oversteer to recognize such generic "input remaper gameped" so it would be possible to do some simple but cool stuff like merging axis (Combine accelerator/clutch pedals)

**Comment by berarma** [comment]
I don't think this makes any sense. Oversteer only changes settings in kernel modules. It couldn't do anything with a virtual device.

**Comment by kopach** [comment]
I see. Do you, maybe, have any other ideas how to combine accelerator/clutch pedals on linux?
I know it's out of scope of this project, just trying to find any possible solution.

**Comment by berarma** [comment]
Couldn't it be implemented into InputMapper?

**Comment by kopach** [comment]
Yes, probably this is the only way to go then. Thanks for your support
