### ISSUE TITLE
Hori Racing Wheel Apex PS3-PS4 Support

### ISSUE THREAD

**Issue by mikeyjoel** [berarma/oversteer#183]
Hi Everyone! Checking in to see if we can add support for the Hori Racing Wheel Apex for Playstation 3 and 4. Here some udev information:
```
[60021.036019] usb 1-9: new full-speed USB device number 21 using xhci_hcd
[60021.180928] usb 1-9: New USB device found, idVendor=0f0d, idProduct=00a4, bcdDevice= 1.01
[60021.180936] usb 1-9: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[60021.180938] usb 1-9: Product: Racing Wheel Apex
[60021.180940] usb 1-9: Manufacturer: HORI CO.,LTD.
[60021.180942] usb 1-9: SerialNumber: 3FFBE831
```

Here from a lsusb and lsusb -t perspective:
`Bus 001 Device 021: ID 0f0d:00a4 Hori Co., Ltd Racing Wheel Apex`
`Class=Vendor Specific Class, Driver=xpad, 12M`

Hopefully, we can work together on getting this baby's tires on the street :)

**Comment by berarma** [comment]
Be aware that I can just add support to Oversteer so that it recognizes the device and accepts its input, but the device needs to be supported by the kernel to work.

It looks like it has been recognized as a gamepad. Maybe that's all that it's needed. If that's the case you won't see much advantage on using Oversteer vs any gamepad/joystick testing tool.

What's the maximum rotation range side to side? Does it have FFB or just a rumble effect?

**Comment by mikeyjoel** [comment]
I was able to get it working with xpad by adding some udev rules. You are correct; it's a new wheel I was getting familiar with, and it doesn't have force feedback of any type. Closing and thank you for your prompt response.

**Comment by poVoq** [comment]
> I was able to get it working with xpad by adding some udev rules. You are correct; it's a new wheel I was getting familiar with, and it doesn't have force feedback of any type. Closing and thank you for your prompt response.

Can you please share the udev rules you used?

**Comment by michaelacostawbd** [comment]
Make sure you have expanded installed and modprobe it
`modprobe xpad`
/etc/udev/rules.d/50-hori-wheel.rules

```
# HORI Racing Wheel Apex
ACTION=="add", ATTRS{idVendor}=="0f0d", ATTRS{idProduct}=="00a4", RUN+="/sbin/modprobe xpad" RUN+="/bin/sh -c 'echo 0f0d 00a4 > /sys/bus/usb/drivers/xpad/new_id'"
```
