### ISSUE TITLE
Wingman Formula Force

### ISSUE THREAD

**Issue by WingmanFF** [berarma/oversteer#188]
I have the Wingman Formula Force and not the Wingman Formula Force GP.
I don't know the difference between the two.
I don't see my wheel in the supported list.
Ubuntu detects my wheel:
I: Bus=0003 Vendor=046d Product=c291 Version=0000
N: Name="Logitech WingMan Formula Force"
P: Phys=
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.4/1-2.4.4/1-2.4.4.2/1-2.4.4.2:1.0/input/input16
U: Uniq=
H: Handlers=event14 js0 
B: PROP=0
B: EV=a0000b
B: KEY=30000 fc000000000 0 0 0 0
B: ABS=30700
B: FF=31f2f0000 100

When starting Oversteer I receive the message: No device available

What should I do or should I forget using this wheel?

**Comment by berarma** [comment]
I know nothing about that wheel except that it's very old.

I can add it to Oversteer in case you're interested. Try it first with evtest to check that it can read all the events and see what each event corresponds to in the wheel.

**Comment by WingmanFF** [comment]
Ok. Since I'm a simple user of Ubuntu, I tried this:
Install evtest.
Used evtest in terminal for my wheel.
It seems that the wheel is detected with all the commands from buttons to brake and gas pedals.
I got this report:
[wingman formula force evtest.docx](https://github.com/berarma/oversteer/files/14559481/wingman.formula.force.evtest.docx)

Thanks for you time.

**Comment by WingmanFF** [comment]
Wingman Formula Force is only one year older than Wingman Formula Force GP, the latter adding a few minors changes from what I read.

https://www.pcgamingwiki.com/wiki/Controller:Logitech_WingMan_Formula
https://www.pcgamingwiki.com/wiki/Controller:Logitech_WingMan_Formula_GP

**Comment by berarma** [comment]
I see it has only 4 buttons but in your document there are 6 buttons and a d-pad, in addition to the wheel axis, two pedals and the shift paddles.

It seems the d-pad and 2 buttons aren't really used even though they're reported by the device as being in use.

**Comment by WingmanFF** [comment]
Yes, I have only 4 buttons, wheel axis, two pedals and the shift paddles.
So, is it possible to add the Wingman force formula to oversteer?
Thanks.

**Comment by berarma** [comment]
Please, can you test the latest master?

**Comment by WingmanFF** [comment]
I don't know how it works when you add the wheel to your database.
I plugged the wheel and open Oversteer and I got no device available.
![Capture d’écran du 2024-03-12 10-05-08](https://github.com/berarma/oversteer/assets/162729802/7efa2660-8613-48f5-a4b2-7d72e512ac0d)
But, the one I have is Logitech Wingman Formula Force, and not, Logitech Wingman Force.
I don't know if it makes a difference.
Wingman Force is with bungee cords, and Wingman Formula Force is built with gears.
Thanks.

**Comment by WingmanFF** [comment]
Still not recognised.
Since I'm not that familiar playing with files in Ubuntu, I did this:
Downloaded new oversteer-master.
Replaced local files after unziping oversteer-master.
From there, I can see that 046d:c291 is listed in /oversteer « wheel_ids.py »
I can see in /oversteer/data/udev « 99-logitech-wheel-perms.rules » that Wingman Formula (Yellow) is put as 046d:c202 but no identification in this file for 046d:c291
Same in /usr/local/lib/udev/rules.d
Should I check another file to see if 046d:c291 is present?
From which file the wheel is recognised?

**Comment by berarma** [comment]
wheel_ids.py

**Comment by WingmanFF** [comment]
Yes, updated wheel_ids.py and I can see in my local file « oversteer » line 27 '046d:c291'

**Comment by vguardiola** [comment]
For me works, the only that don't detect correctly are the shift paddles.

But I think we need to configure it inside new-lg4ff, I'm changing and test the kernel module.

**Comment by WingmanFF** [comment]
Is udev important?
Why are there two different udev files? Should I erase one?
For vguardiola, did you do something different to have the Wingman Formula Force work?

**Comment by berarma** [comment]
> For me works, the only that don't detect correctly are the shift paddles.
> 
> But I think we need to configure it inside new-lg4ff, I'm changing and test the kernel module.

No, it's my mistake. I'll push a new correction here shortly.

**Comment by berarma** [comment]
Please, can you test?

**Comment by berarma** [comment]
> Is udev important? Why are there two different udev files? Should I erase one? For vguardiola, did you do something different to have the Wingman Formula Force work?

Where are two different udev files?

I don't think udev is important to your issue. It looks like an installation / code update issue.

**Comment by vguardiola** [comment]
I only clone the report and build/install it and oversteer detect well the wheel.

**Comment by WingmanFF** [comment]
> > Is udev important? Why are there two different udev files? Should I erase one? For vguardiola, did you do something different to have the Wingman Formula Force work?
> 
> Where are the two different udev files?
> 
> I don't think udev is important to your issue. It looks like an installation / code update issue.

/usr/local/lib/udev/rules.d
and in
/oversteer/data/udev

**Comment by WingmanFF** [comment]
I tried to reload udev rules via the terminal as instructed with 
udevadm control --reload-rules && udevadm trigger
and I got « Failed to send reload request: Permission denied »

**Comment by berarma** [comment]
> > > Is udev important? Why are there two different udev files? Should I erase one? For vguardiola, did you do something different to have the Wingman Formula Force work?
> > 
> > 
> > Where are the two different udev files?
> > I don't think udev is important to your issue. It looks like an installation / code update issue.
> 
> /usr/local/lib/udev/rules.d and in /oversteer/data/udev

The first one is where it gets installed, the second one I guess it's where you have downloaded the source code.

> I tried to reload udev rules via the terminal as instructed with udevadm control --reload-rules && udevadm trigger and I got « Failed to send reload request: Permission denied »

You need to use `sudo` or run it as root.

**Comment by vguardiola** [comment]
I've just pulled your last changes and now the shift paddles are detected

**Comment by WingmanFF** [comment]
I erased the oversteer file and started again from the beginning by cloning as vguardiola did, and followed the steps.
Everything is detected now: All the buttons, shift paddles, steering, pedals, and force feed back.
Many thanks for your work.
