### ISSUE TITLE
Add udev and usb_modeswitch rules for G923 Xbox

### ISSUE THREAD

**Issue by mrchilliballs** [berarma/oversteer#190]
Currently, if you use Oversteer without applying these rules, the steering wheel won't be detected. It would be helpful if Oversteer would apply them on install like the other rules.

This article outlines the files required: https://www.draisberghof.de/usb_modeswitch/bb/viewtopic.php?f=2&p=19927

**Comment by berarma** [comment]
Since there's already a place to put this in (usb_modeswitch), I think it should be placed there.
