### ISSUE TITLE
T300 RS GT buttons aren't recognised in the program

### ISSUE THREAD

**Issue by FelipeMelon** [berarma/oversteer#191]
Whenever I click buttons on my wheel they're not being highlighted in the program, except L3 and R3, so I have no idea on what to do.

**Comment by berarma** [comment]
We can take a look at the vendor/product ids and the events those buttons generate.

This can be done with `evtest`. Just run the command in a terminal and select the device, then it will show some information you can copy/paste here. Press all the buttons one by one and annotate the events generated for each button. Again, you can copy/paste but annotating which button generated which event.

**Comment by berarma** [comment]
The button events are correctly listed but the events don't arrive. Strange, I think it's worked before for other users with the same wheel.

Is the wheel connected to a USB hub? Some switch in the wheel which you can try toggling? I'm not familiar with that device.

**Comment by berarma** [comment]
Since this an issue with the wheel, not Oversteer, you might want to ask for help in the [hid-tmff2 project](https://github.com/Kimplul/hid-tmff2). I can't help much. Sorry.
