### ISSUE TITLE
gksudo is not included now in Debian and Ubuntu

### ISSUE THREAD

**Issue by leillo1975** [berarma/oversteer#2]
Since a little time, "gksudo" is not included on Debian and Ubuntu .To use your app I need to install the rest of the dependencies, and then execute the program with sudo. You can see more information about the abandonement and alternatives to gksudo here:

https://itsfoss.com/gksu-replacement-ubuntu/

I would also like to congratulate you and thank you for your application.

**Comment by berarma** [comment]
Good heads up. It doesn't seem obvious how to replace it in this case. It seems I should use pkexec but I have to figure out how to use it in a graphical environment.

**Comment by berarma** [comment]
The fix was easy. It didn't work for me before because I was trying to use pkexec from a remote X session.
