### ISSUE TITLE
Hey im also having issues with the permissions.

### ISSUE THREAD

**Issue by berarma** [berarma/oversteer#208]
Hey im also having issues with the permissions. 

During the install the rules were installed to /usr/local/lib/udev/rules.d and on launching oversteer after a reboot I get the permissions error. 

I have moved the rules file to /etc/udev/rules.d and still I receive the same permission denied error when launching oversteer. 

I initially moved the file to /etc/udev/rules.d using nano though this did not fix it so I went back and tried as advised above meson configure -Dudev_rules_dir= build and followed the install again though is has not resolved the issue. 

Im sure its something daft as im also new to linux, any help would be appreciated thanks. 

debug report below: 

versteer --debug
DEBUG:root:update_device_list: /devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E/input/input14/event13 /dev/input/event13
DEBUG:root:/dev/input/event13: ID_VENDOR_ID: 044f ID_MODEL_ID: b66e
DEBUG:root:Devices: {'/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E/input/input14/event13': <oversteer.device.Device object at 0x783aafdab920>}
DEBUG:root:/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E/input/input14/event13: {'device_manager': <oversteer.device_manager.DeviceManager object at 0x783aafdabaa0>, 'input_device': None, 'id': '/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E/input/input14/event13', 'vendor_id': '044f', 'product_id': 'b66e', 'usb_id': '044f:b66e', 'dev_path': '/sys/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E', 'dev_name': '/dev/input/event13', 'name': 'Thrustmaster Thrustmaster T300RS Racing wheel', 'ready': True, 'max_range': 1080}
DEBUG:matplotlib:matplotlib data path: /usr/share/matplotlib/mpl-data
DEBUG:matplotlib:CONFIGDIR=/home/marcus/.config/matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:CACHEDIR=/home/marcus/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/marcus/.cache/matplotlib/fontlist-v330.json
DEBUG:root:populate_devices
DEBUG:root:check_permissions: /sys/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E
DEBUG:root:check_file_permissions mode: 0o644 user: root group: root file: /sys/devices/pci0000:00/0000:00:08.1/0000:0b:00.3/usb3/3-3/3-3.4/3-3.4:1.0/0003:044F:B66E.000E/alternate_modes
DEBUG:root:flush_device
DEBUG:root:Setting autocenter strength: 0
DEBUG:root:Setting FF gain: 65535
DEBUG:root:flush_ui

_Originally posted by @1hom in https://github.com/berarma/oversteer/issues/207#issuecomment-2138192884_

**Comment by berarma** [comment]
I guess you have rebooted every time something changed in the udev rules. I have to ask to make sure we're not missing the obvious.

There seems to be differences in the handling of udev rules from distro to distro. I can't test in all of them. In truth, udev rules should rather be installed by the distro but since none does I'm inlcuding them in Oversteer to make it easier for the user.

Since you've already tried installing the rules in the system directory and it doesn't work, I think you should ask in the forum of your distro. They might know better than me why the rules aren't working. If they find something wrong with the rules please report back and I'll try to fix it.

**Comment by 1hom** [comment]
Hey I have asked and from what I have been advised the way i have been trying to create/recreate or move the udev rules files are fine and would/should not cause an issue, however since realizing I can run oversteer from the terminal as sudo and it seems to work fine  like this im happy.
