### ISSUE TITLE
Logitech G923 wheel not found in debian

### ISSUE THREAD

**Issue by enffinity** [berarma/oversteer#210]
wheel is shown when doing `lsusb` but otherwise when running oversteer it says no device found and when doing `oversteer --list` it shows no devices, is there any way to add the device manually?

**Comment by berarma** [comment]
What's the output of lsusb?

**Comment by thenicnet** [comment]
I'm in a similar situation. I'm on POP_OS 22.04 LTS.
I've got a Logitech G29 (PS4) version. I just installed [new-lg4ff](https://github.com/berarma/new-lg4ff) and I can confirm I can see the wheel via lsusb and in dmesg, but when I launch oversteer it doesn't pick it up. I can create a separate issue for this if you like, but it seems to be a similar vein.

**Comment by berarma** [comment]
> I'm in a similar situation. I'm on POP_OS 22.04 LTS.
> I've got a Logitech G29 (PS4) version. I just installed [new-lg4ff](https://github.com/berarma/new-lg4ff) and I can confirm I can see the wheel via lsusb and in dmesg, but when I launch oversteer it doesn't pick it up. I can create a separate issue for this if you like, but it seems to be a similar vein. 

It has to be in PS3 mode. Check the switch       at the front of the wheel.

**Comment by thenicnet** [comment]
> > I'm in a similar situation. I'm on POP_OS 22.04 LTS.
> > I've got a Logitech G29 (PS4) version. I just installed [new-lg4ff](https://github.com/berarma/new-lg4ff) and I can confirm I can see the wheel via lsusb and in dmesg, but when I launch oversteer it doesn't pick it up. I can create a separate issue for this if you like, but it seems to be a similar vein.
> 
> It has to be in PS3 mode. Check the switch at the front of the wheel.

That did it. I am embarrassed I didn't try that.
Thank you.

**Comment by berarma** [comment]
> > What's the output of lsusb?
> 
> I fixed it by running a command listed on the arch linux wiki (sudo usb_modeswitch -v 046d -p c26d -M 0f00010142 -C 0x03 -m 01 -r 01)

Yes, that's needed to change the wheel mode for Linux compatibility. It's usually done via a udev rule, I'm surprised this has to be done manually since it's usually integrated into the system.
