### ISSUE TITLE
Cannot save Profile and Settings are reset after reboot

### ISSUE THREAD

**Issue by Simon-Sonnleitner** [berarma/oversteer#217]
I cannot click the "save" button and  the "profile" button just opens a very small drop down menu in which I can neither see nor click on anything. I tried to save the profile as a config file and went to `~/.config/oversteer/profiles` which was empty and I don't know in what format I should save my settings

**Comment by Henry-Hiles** [comment]
> I cannot click the "save" button and the "profile" button just opens a very small drop down menu in which I can neither see nor click on anything. I tried to save the profile as a config file and went to `~/.config/oversteer/profiles` which was empty and I don't know in what format I should save my settings

Same here. Are you on nix too?

**Comment by berarma** [comment]
Have you tried clicking the New button in the Profiles tab?

**Comment by Simon-Sonnleitner** [comment]
> > I cannot click the "save" button and the "profile" button just opens a very small drop down menu in which I can neither see nor click on anything. I tried to save the profile as a config file and went to `~/.config/oversteer/profiles` which was empty and I don't know in what format I should save my settings
> 
> Same here. Are you on nix too?

I'm on Arch with Hyprland

**Comment by Simon-Sonnleitner** [comment]
> Have you tried clicking the New button in the Profiles tab?
Oh, yeah... I'm sorry, I completely overlooked it.
After creating a new Profile in this tab I can now select it in the dropdown menu
