### ISSUE TITLE
(Back here again/Linux newbie)

### ISSUE THREAD

**Issue by bugerkin** [berarma/oversteer#224]
So I'm back here since I upgraded for Linux mint 21.3 to 22 and I wanted to reinstall oversteer since I reinstalled Linux mint and I can't find all the dependency for creating oversteer from scratch. Is Mint 22 too new? (I was able to install and use oversteer on 21.3)

(I also tried using the flatpack version but I couldn't figure out the udev problems I had last time since I could find the file I changed last time to fix the problem.

Problem I had last time: https://github.com/berarma/oversteer/issues/207

![Screenshot from 2024-08-04 23-57-07](https://github.com/user-attachments/assets/7e9f88ed-dd85-4675-a32b-fdc916a90f0e)

**Comment by jo5huajohn** [comment]
Hi, could you let me know more about the issues with the flatpak? I'm assuming you installed the udev rules manually. Unfortunately, there is no recommended way for the flatpak to install udev rules on the system, so users have to manually install it.

**Comment by bugerkin** [comment]
Besides oversteer, I don't think I installed udev rules last time since I just edited one of the files to fix the problem after making oversteer from source in my last issue: https://github.com/berarma/oversteer/issues/207. Also is there a guide you could link to me for installing udev rules for Mint 22 or at least tell me how I can do this.

**Comment by jo5huajohn** [comment]
You should copy the files to /etc/udev/rules.d or /usr/local/lib/udev/rules.d.

**Comment by bugerkin** [comment]
I can't do that if I can't find the dependency's for mint 22 to make oversteer from source. Also the flatpak didn't have those directory's with the files or if it does then I don't know how to find them.

**Comment by jo5huajohn** [comment]
Its in the oversteer git repo.

**Comment by berarma** [comment]
> I can't do that if I can't find the dependency's for mint 22 to make oversteer from source. Also the flatpak didn't have those directory's with the files or if it does then I don't know how to find them.

https://github.com/berarma/oversteer/tree/master/data/udev

**Comment by bugerkin** [comment]
So I downloaded the files and I couldn't move it to /etc/udev/rules.d because of permission issues and I can't move it /usr/local/lib/udev/rules.d because the file directory doesn't exist.

I've even tried using sudo nemo and I still couldn't transfer the file from my download folder.

![Screenshot from 2024-08-08 01-50-30](https://github.com/user-attachments/assets/3a2217bd-a9b4-49d2-b5e1-5dbbec932063)
![Screenshot from 2024-08-08 01-51-28](https://github.com/user-attachments/assets/4fcff4a7-4994-4ebe-a4cd-a39071ea5a7b)

**Comment by berarma** [comment]
Show more details?

**Comment by bugerkin** [comment]
I give up

**Comment by bugerkin** [comment]
I give up
