### ISSUE TITLE
T300RS not detected

### ISSUE THREAD

**Issue by TobyJ-B** [berarma/oversteer#229]
Device not detected

Output of lsusb
![image](https://github.com/user-attachments/assets/610b2339-4dcc-414c-aef0-8214e460d95b)

**Comment by berarma** [comment]
Could you specify which distro are you running? Also the Oversteer version.

There's already two other users with detection problems (#225), I wonder whether is related.

**Comment by TobyJ-B** [comment]
Running latest version of arch linux with latest version of oversteer from the AUR

**Comment by TobyJ-B** [comment]
Running arch linux with the latest version from the AUR

**Comment by TobyJ-B** [comment]
Fixed by updating firmware
