### ISSUE TITLE
How to make Oversteer not start on system startup?

### ISSUE THREAD

**Issue by sBinnotto16** [berarma/oversteer#249]
Wheel: Thrustmaster T248
Distro: OpenSUSE Tumbleweed
Oversteer version: 0.8.3 (from Open Build Service)

Pressing the "Start application manually button" doesnt save the setting without the wheel plugged in. With the wheel I have it saved both in default and custom profiles but it still doesnt work.

**Comment by berarma** [comment]
That setting is for the application supplied in the command line. There should be a bit more explanation.

If Oversteer is being started on system startup, that's probably the package you have installed that puts it in `$HOME/.config/autostart/`.
