### ISSUE TITLE
Saving a profile resets everything

### ISSUE THREAD

**Issue by berarma** [berarma/oversteer#29]
I can confirm the problem.
I Just updated from 0.4.1 to 0.5.0 and Profiles doesnt work anymore.
Changes will take effect, but clicking the 'save' button will reset everything.
Back on 0.4.1 everythings fine.

One Question:
Where is the storage location of the profiles?

Thanks for your great work.
I love it.

Helge

_Originally posted by @Helge102 in https://github.com/berarma/oversteer/issues/28#issuecomment-685070487_

**Comment by berarma** [comment]
Can you run Oversteer from the command line and paste the output in case there's some error?

Also, please, attach the profile file before and after the error.

The profile files are located in $XDG_CONFIG_HOME/oversteer/profiles, typically $HOME/.config/oversteer/profiles.

Thanks.

**Comment by Helge102** [comment]
Sorry for waiting.
I have to reinstall the version 0.5.0 first to get results.
But I can already say that no errors were displayed on the command line.

Helge

**Comment by Helge102** [comment]
Is it necessary to uninstall version 0.4.1 or should an update to 0.5.0 work?
Last time I made an update and it came up with the problem with the profiles.

Helge

**Comment by berarma** [comment]
Just install the newest version, 0.5.3 at the moment.

**Comment by thcobl** [comment]
when i download and install again it still says that its version 0.5.0 and i still can not save my profiles

**Comment by thcobl** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/oversteer/gtk_handlers.py", line 145, in on_save_profile_clicked
    self.controller.save_profile(profile_name)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 205, in save_profile
    profile = Profile(self.model.to_dict())
  File "/usr/lib/python3.8/site-packages/oversteer/profile.py", line 11, in __init__
    self.set_combine_pedals(data['combine_pedals'])
  File "/usr/lib/python3.8/site-packages/oversteer/profile.py", line 59, in set_combine_pedals
    self.set('combine_pedals', int(combine_pedals))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by thcobl** [comment]
i think i have it running now :) but still its says 0.5.0 and i get this (oversteer:1853): Gtk-CRITICAL **: 11:36:28.750: gtk_cell_view_set_displayed_row: assertion 'GTK_IS_TREE_MODEL (cell_view->priv->model)' failed
and if i save it sets my rotation range back to 270  ( i have a logitech momo )

**Comment by berarma** [comment]
> Traceback (most recent call last):
> File "/usr/lib/python3.8/site-packages/oversteer/gtk_handlers.py", line 145, in on_save_profile_clicked
> self.controller.save_profile(profile_name)
> File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 205, in save_profile
> profile = Profile(self.model.to_dict())
> File "/usr/lib/python3.8/site-packages/oversteer/profile.py", line 11, in **init**
> self.set_combine_pedals(data['combine_pedals'])
> File "/usr/lib/python3.8/site-packages/oversteer/profile.py", line 59, in set_combine_pedals
> self.set('combine_pedals', int(combine_pedals))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

You're using the master branch. There are still some issues there with profiles and features not supported by the wheel.

I'm fixing them but you may want to download a release or use the `0.5.x` branch meanwhile.

> i think i have it running now :) but still its says 0.5.0 and i get this (oversteer:1853): Gtk-CRITICAL **: 11:36:28.750: gtk_cell_view_set_displayed_row: assertion 'GTK_IS_TREE_MODEL (cell_view->priv->model)' failed
> and if i save it sets my rotation range back to 270 ( i have a logitech momo )

The error might be related to what's new in master. I'll try to reproduce the error and fix it.

Sorry, I've forgotten to update the version number for all the latest point releases. Even changing to the `0.5.x` branch you'll still see 0.5.0 until fixed in a new release.

Your wheel doesn't support a different range so it'll always be 270. I have to implement per wheel ranges.

**Comment by thcobl** [comment]
thx :)

**Comment by thcobl** [comment]
i have it working now  but in gui when i push accel i see the clutch and when i push brake i see accel

**Comment by thcobl** [comment]
and every time i start oversteer it ask me again about udev rules

**Comment by berarma** [comment]
> i have it working now but in gui when i push accel i see the clutch and when i push brake i see accel

Which wheel are you using? That sounds like a problem with the G920 that was fixed some in the 0.5.0 release.

**Comment by thcobl** [comment]
im using a logitech momo

**Comment by berarma** [comment]
> im using a logitech momo

OK, I'll fix it based on the info you gave me.

> and every time i start oversteer it ask me again about udev rules

Even if you answer affirmatively do you get asked again?

I think this is the first report on that wheel. I can try to fix all the issues with your help.

**Comment by thcobl** [comment]
yes it keeps asking it every time 
and yes its an old wheel so im happy someone makes it working :)

**Comment by berarma** [comment]
@thcobl, I've oppened #40 for your issues.

Closing this ticked since there's no enough info and I can't reproduce it.

**Comment by nawordar** [comment]
I have now a very similar problem — when I hit the Save button, all sliders in the Force Feedback are reset. I have no messages in the console and when I edit .ini file manually, it loads just fine.

Also, a weird thing happens: yay shows that I have installed version 0.5.5-1 from the AUR, but both `oversteer --version` and the About window show version 0.5.0. `type oversteer` shows `/usr/bin/oversteer`.

**Comment by isopix** [comment]
Yay, you learned me about 'type' command.
Other usable commands for you would be 'which' and  'whereis'
Also  pacman -Ql oversteer

I've checked and it's true:
 oversteer --version
Oversteer v0.5.0

And because:
pkgver=0.5.5
source=("$pkgname-$pkgver.tar.gz::https://github.com/berarma/${pkgname}/archive/${pkgver}.tar.gz")


It means the problem lies in berarma's github archive.

**Comment by berarma** [comment]
There's been a lot of fixes since that version. Could you try with the latest gihub code? I think your problem is already solved. I'll try to make another release as soon as possible but I'd like the code to be tested.

**Comment by nawordar** [comment]
@berarma it works great, thanks. I had to rename `~/.config/oversteer/config.ini` as pointed out in another issue, though.
