### ISSUE TITLE
Wrong number type when changing master gain on Ubuntu 20.04

### ISSUE THREAD

**Issue by Kimplul** [berarma/oversteer#38]
When changing autocentering or gain values, Python spits out
```
Traceback (most recent call last):
  File "/home/kimi/Documents/oversteer/oversteer/gtk_handlers.py", line 101, in on_autocenter_value_changed
    self.model.set_autocenter(autocenter)
  File "/home/kimi/Documents/oversteer/oversteer/model.py", line 154, in set_autocenter
    self.device.set_autocenter(value * 65535 / 100)
  File "/home/kimi/Documents/oversteer/oversteer/device.py", line 191, in set_autocenter
    input_device.write(ecodes.EV_FF, ecodes.FF_AUTOCENTER, int(autocenter))
ValueError: invalid literal for int() with base 10: '0.0'
```

The latest commit that still worked was  d257e70, and the fix seems to be to just replace `value * 65535 / 100` on lines 146 and 154 in model.py with `int(value * 65535 / 100)`. No clue why it doesn't work on Ubuntu, but does work on Debian.

EDIT: Sorry, got mixed up, the first commit that causes these errors is d257e70.

**Comment by berarma** [comment]
Have you tried it on Debian?

The reason it works for me and others is because `set_autocenter` uses sysfs when the autocenter entry is available or writes to the device when it's not. Your driver is triggering the second case which runs the line with the error.

It'll be fixed shortly.

**Comment by berarma** [comment]
Please, pull from master and test. Thanks!

**Comment by Kimplul** [comment]
Yep, Debian it works just fine. Pulled from master, clean build, etc.

**Comment by berarma** [comment]
Have you tried the latest commit? It should be already fixed.

**Comment by Kimplul** [comment]
Yep, all is well. Thanks a lot.

**Comment by berarma** [comment]
I don't know why it worked for you on Debian, I've just tested on my system and that code failed too. The only reason might be the presence of the `autocenter` entry in sysfs.
