### ISSUE TITLE
T300RS range can't be set to 1080°

### ISSUE THREAD

**Issue by Kimplul** [berarma/oversteer#42]
The UI shows 1080° degrees, but the slider can't be pulled up higher than 900°. Fiddling around with `main.ui` I figured out that changing line 578, `<property name="fill-level">90</property>` to `<property name="fille-level">108</property>` fixes the issue for me, but I don't know if it affects wheels that can only go up to 900°.

**Comment by berarma** [comment]
Thanks for the report. Please, check the fix since I don't have a TM wheel to test.

**Comment by Kimplul** [comment]
Yep, works as expected, thank you.
