### ISSUE TITLE
Logitech Wheel 923 doesn't show as an option in Oversteer

### ISSUE THREAD

**Issue by McDaver** [berarma/oversteer#44]
I am running Ubuntu 18.04.5 and installed Oversteer.  After a reboot and running Oversteer with my G923 wheel plugged in, it's not detected as an option in the Oversteer dropdown selection box.  I checked in HWINFO for the Logitech wheel and it does show up.  Am I missing something and this should work, or can someone add support for the G923?  From my understanding it should be compatible with all G29/G920 functions.  I can test if a change is made.
Here is the info from my Linux HWINFO list.

89: USB 00.0: 0000 Unclassified device
  [Created at usb.122]
  Unique ID: Uc5H.W3ivzdKOzY1
  Parent ID: k4bc.029GFTetOb3
  SysFS ID: /devices/pci0000:00/0000:00:01.3/0000:03:00.0/usb1/1-4/1-4:1.0
  SysFS BusID: 1-4:1.0
  Hardware Class: unknown
  Model: "Logitech G923 Racing Wheel for Xbox One and PC"
  Hotplug: USB
  Vendor: usb 0x046d "Logitech, Inc."
  Device: usb 0xc26d "G923 Racing Wheel for Xbox One and PC"
  Revision: "39.01"
  Serial ID: "0000f2b79b162e71"
  Speed: 12 Mbps
  Module Alias: "usb:v046DpC26Dd3901dcFFdscFFdpFFicFFisc47ipD0in00"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #88 (Hub)

**Comment by berarma** [comment]
Please see #37.

**Comment by ZRtmWrJqXcjbqBLIMBYMCeUw** [comment]
@berarma With the merge of #37, this should be closed now. @McDaver The G923 wheel does not yet have full support but can be made to work using the patch submitted in this pull request: berarma/new-lg4ff#50 as well as running `usb_modeswitch` or simply adding the udev rule mentioned by @JacKeTUs in their original comment on that same pull request.

**Comment by berarma** [comment]
Thanks for reminding me of this issue. This is for the XBox version. It's not supported by new-lg4ff and never will since it's more similar to a G920.

It's not recognized by Oversteer either but I can add it. I'll need that someone confirms that it works correctly.

**Comment by ZRtmWrJqXcjbqBLIMBYMCeUw** [comment]
Sorry, missed the part about this being the XBox version. Not sure if OP already did this, but the patches in [this series](https://patchwork.kernel.org/project/linux-input/list/?series=489571) need to be added to kernel. There is an issue with the second patch which should be easily fixable, as I describe [here](https://github.com/ZRtmWrJqXcjbqBLIMBYMCeUw/Logitech-G923-Linux-Kernel-Driver#g923-xbox-version).

**Comment by kevin1zc** [comment]
G923 XBOX version still doesn't show up. I tried it both with and without the ```new-lg4ff``` package but neither worked. ```lsusb``` recognizes the device but ```cat /proc/bus/input/devices | grep Logitech``` gives me nothing.

```lsusb``` output: 
```
Bus 001 Device 010: ID 046d:c26d Logitech, Inc. G923 Racing Wheel for Xbox One and PC
```

```sudo dmesg``` output:
```
[    6.038176] usb 1-12: new full-speed USB device number 10 using xhci_hcd
[    6.188093] usb 1-12: New USB device found, idVendor=046d, idProduct=c26d, bcdDevice=39.01
[    6.188106] usb 1-12: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    6.188111] usb 1-12: Product: G923 Racing Wheel for Xbox One and PC
[    6.188115] usb 1-12: Manufacturer: Logitech
[    6.188119] usb 1-12: SerialNumber: 0000a844d92b842c
```
Note that it is not recognized as an HID device. ```sudo dmesg | grep hid``` output:
```
[    6.757194] hid: raw HID events driver (C) Jiri Kosina
[    6.762261] usbhid 1-8:1.2: couldn't find an input interrupt endpoint
[    6.766367] usbcore: registered new interface driver usbhid
[    6.766368] usbhid: USB HID core driver
[    6.826577] hid-generic 0003:03F0:098D.0001: input,hiddev0,hidraw0: USB HID v1.00 Device [HP, Inc HyperX Cloud Alpha Wireless] on usb-0000:00:14.0-5/input3
[    6.827182] hid-generic 0003:1532:007B.0002: input,hidraw1: USB HID v1.11 Mouse [Razer Razer Viper Ultimate Dongle] on usb-0000:00:14.0-4.1/input0
[    6.886888] hid-generic 0003:1532:007B.0003: input,hidraw2: USB HID v1.11 Keyboard [Razer Razer Viper Ultimate Dongle] on usb-0000:00:14.0-4.1/input1
[    6.946599] hid-generic 0003:1532:007B.0004: input,hidraw3: USB HID v1.11 Keyboard [Razer Razer Viper Ultimate Dongle] on usb-0000:00:14.0-4.1/input2
[    6.947451] hid-generic 0003:1532:007E.0005: input,hidraw4: USB HID v1.11 Mouse [RAZER Razer Mouse Dock] on usb-0000:00:14.0-4.2/input0
[    7.006875] hid-generic 0003:1532:007E.0006: input,hidraw5: USB HID v1.11 Keyboard [RAZER Razer Mouse Dock] on usb-0000:00:14.0-4.2/input1
[    7.066611] hid-generic 0003:1532:007E.0007: input,hidraw6: USB HID v1.11 Keyboard [RAZER Razer Mouse Dock] on usb-0000:00:14.0-4.2/input2
[    7.126513] hid-generic 0003:062A:38C2.0008: input,hidraw7: USB HID v1.11 Keyboard [MosArt Varmilo Keyboard] on usb-0000:00:14.0-9/input0
[    7.187421] hid-generic 0003:062A:38C2.0009: input,hiddev1,hidraw8: USB HID v1.11 Device [MosArt Varmilo Keyboard] on usb-0000:00:14.0-9/input1
[    7.187989] hid-generic 0003:048D:5702.000A: hiddev2,hidraw9: USB HID v1.12 Device [ITE Tech. Inc. ITE Device] on usb-0000:00:14.0-13/input0
```

**Comment by berarma** [comment]
You don't need new-lg4ff, you better don't use it.

Your wheel is in XBOX mode. If it works the same way as the G920, your distro should be configured by default to switch to PC mode using udev and usb-modeswitch. You could ask in the support forums of your distro.

**Comment by kevin1zc** [comment]
> You don't need new-lg4ff, you better don't use it.
> 
> Your wheel is in XBOX mode. If it works the same way as the G920, your distro should be configured by default to switch to PC mode using udev and usb-modeswitch. You could ask in the support forums of your distro.

Thank you for your reply. I tested both G920 and G923 on 2 separate machines with Ubuntu 20.04. G920 worked out of box on both machines but G923 didn't. Ubuntu has udev and usb-modeswitch installed by default but somehow they didn't work for G923. Do you have any suggestion on how to fix it?

**Comment by berarma** [comment]
The missing piece might be this: https://www.draisberghof.de/usb_modeswitch/bb/viewtopic.php?f=2&p=19927

You can try the equivalent command before creating those files. It would be (run as administrator):

`usb_modeswitch -v 046d -p c26d -M 0f00010142 -C 0x03 -m 01 -r 01`

After running the command the USB product ID should change to `046d:c26e`.

If that's the case it should be already recognized by Oversteer.

**Comment by kdw2060** [comment]
Hi, after executing the command `usb_modeswitch -v 046d -p c26d -M 0f00010142 -C 0x03 -m 01 -r 01`, I get this output:

```
Look for target devices ...
 No devices in target mode or class found
Look for default devices ...
 Found devices in default mode (1)
Access device 011 on bus 001
Get the current device configuration ...
Current configuration number is 1
Use interface number 0
 with class 255
Use endpoints 0x01 (out) and 0x01 (in)
Looking for active drivers ...
Set up interface 0
Use endpoint 0x01 for message sending ...
Trying to send message 1 to endpoint 0x01 ...
 OK, message successfully sent

Reset response endpoint 0x01
Reset message endpoint 0x01
 Could not reset endpoint (probably harmless): -99
 Device is gone, skip any further commands
-> Run lsusb to note any changes. Bye!
```

The wheel is found by Oversteer, but when i use any of the controls nothing happens in the Oversteer window. Also commands from Oversteer like centering don't work.

I guess the 'Device is gone' line indicates an issue. Can anyone please advise me how to proceed to further debug?

Environment:
* using the xbox-version of the G923
* running Nobara distro
* using Flatpak version of Oversteer (0.8.3)
* udev rule files have been copied to `/usr/lib/udev/rules.d`

**Comment by berarma** [comment]
> Hi, after executing the command `usb_modeswitch -v 046d -p c26d -M 0f00010142 -C 0x03 -m 01 -r 01`, I get this output:
> 
> ```
> Look for target devices ...
>  No devices in target mode or class found
> Look for default devices ...
>  Found devices in default mode (1)
> Access device 011 on bus 001
> Get the current device configuration ...
> Current configuration number is 1
> Use interface number 0
>  with class 255
> Use endpoints 0x01 (out) and 0x01 (in)
> Looking for active drivers ...
> Set up interface 0
> Use endpoint 0x01 for message sending ...
> Trying to send message 1 to endpoint 0x01 ...
>  OK, message successfully sent
> 
> Reset response endpoint 0x01
> Reset message endpoint 0x01
>  Could not reset endpoint (probably harmless): -99
>  Device is gone, skip any further commands
> -> Run lsusb to note any changes. Bye!
> ```
> 
> The wheel is found by Oversteer, but when i use any of the controls nothing happens in the Oversteer window. Also commands from Oversteer like centering don't work.
> 
> I guess the 'Device is gone' line indicates an issue. Can anyone please advise me how to proceed to further debug?
> 
> Environment:
> 
>     * using the xbox-version of the G923
> 
>     * running Nobara distro
> 
>     * using Flatpak version of Oversteer (0.8.3)
> 
>     * udev rule files have been copied to `/usr/lib/udev/rules.d`

The "device is gone" message could mean that the device with id 0xc26d has disappeared and a new device with id 0xc26e should have appeared. Can you test the device with jstest or evtest?

Please, could you put this in a new issue so cases don't get mixed?
