### ISSUE TITLE
Logitech WingMan Formula Force GP not supported

### ISSUE THREAD

**Issue by Zuikkis** [berarma/oversteer#46]
Hi!

Title says it all.. :) Force GP is not detected, and as I read the README it's not on the list of supported devices.

The wheel is supported by kernel, and also by your new-lg4ff. :)

To make things more complicated, my wheel is actually a Momo Force which has it's controller chip replaced from Force GP. More details on this insanity at https://zuikk.is/momo/start

Anyway on software side it should be exactly as Force GP, except perhaps slightly different ranges on the pedals.

**Comment by berarma** [comment]
I've added the missing Wingman Formula models. You'll have to update to the latest master version.

Please, test it with your wheel and report back on what's working or not related to the hardware.

**Comment by Zuikkis** [comment]
Hmm, it still doesn't find any devices. Perhaps there is some other issue? I don't have other wheels so, I'm not sure if it works at all? :)

```
# lsusb |grep -i logitech
Bus 001 Device 011: ID 046d:c293 Logitech, Inc. WingMan Formula Force GP

```

I looked at your changes, that's exactly the ID that you have added.

**Comment by berarma** [comment]
Please, update the code again, install, run `oversteer --debug` in the console and paste the output here.

**Comment by Zuikkis** [comment]
```
tsuikki@puucee:~$ oversteer --list
Devices found:
tsuikki@puucee:~$ oversteer --debug
DEBUG:root:Devices: {}
tsuikki@puucee:~$ 

```

Not very useful.. ;(

But the wheel is working in games, and I can even run the "fftest" command line test.

**Comment by Zuikkis** [comment]
Hmm, is it possible it's somehow running the old version? All files are replaced by install. I'll try rebooting just in case.

**Comment by berarma** [comment]
Try running the list command as root. Please make sure you have the latest changes from master branch.

**Comment by Zuikkis** [comment]
I know where the bug is.. :)

```
    LG_G29 = '046d:c24f'
    LG_G920 = '046d:c262'
    LG_DF = '046d:c294'
    LG_MOMO = '046d:c295'
    LG_DFP = '046d:c298'
    LG_G25 = '046d:c299'
    LG_DFGT = '046d:c29a'
    LG_G27 = '046d:c29b'
    LG_SFW = '046d:c29c'
    LG_MOMO2 = '046d:ca03'
    LG_WFG = '046d:c20e',
    LG_WFFG = '046d:c293',
    TM_T300RS = '044f:b66e'

```

See there's commas after the lines you added.. )

**Comment by berarma** [comment]
Great, good catch. I'll fix it later.

**Comment by Zuikkis** [comment]
It's working now that I fixed it. Only issue remains, oversteer complains about the udev permissions and wants to install a rule. However that does not fix it, even after reboot it complains it again. 

I get this in syslog:

`Jan  2 22:51:05 puucee systemd-udevd[4190]: 0003:046D:C293.000A: Process '/bin/sh -c 'cd /sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/usb1/1-9/1-9:1.0/0003:046D:C293.000A/../../../; chmod 666 range gain autocenter spring_level damper_level friction_level ffb_leds peak_ffb_level'' failed with exit code 1.
`
There's a few things I notice.. 

What's with the /../../../ in the path end? The listed files are found in the directory ending in 000A, not three levels up. So the doesn't find the files.

All the files are there and have 666 mode already, except for ffb_leds which is missing completely since Force GP has no leds. So perhaps that triggers the permission warning in oversteer? 

I tested oversteer briefly and it seems to work, great. :)

**Comment by berarma** [comment]
I've removed the commas in a new commit.

> What's with the /../../../ in the path end? The listed files are found in the directory ending in 000A, not three levels up. So the doesn't find the files.

I have those messages too. It seems to be working though but I don't know if this has always happened or something has changed. I'll investigate what's happening.

> All the files are there and have 666 mode already, except for ffb_leds which is missing completely since Force GP has no leds. So perhaps that triggers the permission warning in oversteer?

Missing files are ignored by the check. It should be something else. Can you paste the output of `ls -l` in that directory?

**Comment by Zuikkis** [comment]
```
-rw-rw-rw- 1 root root 4096 tammi   2 23:04 autocenter
-rw-rw-r-- 1 root root 4096 tammi   2 22:52 combine_pedals
-r--r--r-- 1 root root 4096 tammi   2 22:52 country
-rw-rw-rw- 1 root root 4096 tammi   2 22:51 damper_level
lrwxrwxrwx 1 root root    0 tammi   2 22:51 driver -> ../../../../../../../../bus/hid/drivers/logitech
-rw-rw-rw- 1 root root 4096 tammi   2 22:51 friction_level
-rw-rw-rw- 1 root root 4096 tammi   2 22:51 gain
drwxr-xr-x 3 root root    0 tammi   2 22:51 hidraw
drwxr-xr-x 3 root root    0 tammi   2 22:51 input
-r--r--r-- 1 root root 4096 tammi   2 22:52 modalias
-rw-rw-rw- 1 root root 4096 tammi   2 22:51 peak_ffb_level
drwxr-xr-x 2 root root    0 tammi   2 22:52 power
-rw-rw-rw- 1 root root 4096 tammi   2 23:02 range
-r--r--r-- 1 root root 4096 tammi   2 22:51 report_descriptor
-rw-rw-rw- 1 root root 4096 tammi   2 22:51 spring_level
lrwxrwxrwx 1 root root    0 tammi   2 22:51 subsystem -> ../../../../../../../../bus/hid
-rw-r--r-- 1 root root 4096 tammi   2 22:51 uevent

```

There... Looks good? Still oversteer complains about the permissions.

**Comment by Zuikkis** [comment]
![kuva](https://user-images.githubusercontent.com/6397305/103471731-4008a280-4d8c-11eb-8ad0-1788d5de598d.png)

BTW, probably a different issue but the steering display is way off. I have the wheel centered and it shows like that. It only moves a few pixels when I turn the wheel. The actual range shown with "evtest" and "evdev-joystick" is 0..1023, I think oversteer assumes 0..65535 or something?

**Comment by Zuikkis** [comment]
combine_pedals permission is 665, not 666. And looking at the udev rule, it doesn't set that file. :)

**Comment by berarma** [comment]
Both issues should be fixed now. Please, update and test again.

**Comment by Zuikkis** [comment]
Yes, perfect now! Thanks a lot for your quick service. :)

**Comment by berarma** [comment]
Thank you for the help.
