### ISSUE TITLE
Installing on Fedora fails

### ISSUE THREAD

**Issue by markonius** [berarma/oversteer#50]
`ninja -C build install` fails on Fedora 33.
It installs all the files into `/usr/lib/python3.9/site-packages/`, but then it tries `Listing '/usr/local/lib/python3.9/site-packages/oversteer'...` and fails. Note that the directories differ. After copying the files manually it works.

**Comment by berarma** [comment]
It was failing at the compilation step that wasn't really needed. I think it was failiing for everyone indeed. Still worth a fix though. Thanks.
