### ISSUE TITLE
Application doesn't start under Garuda Linux

### ISSUE THREAD

**Issue by z4ri0n** [berarma/oversteer#51]
Hi, I've installed Oversteer with Garuda Gamer application, all dependencies are satisfied, but launching under the GUI the application doesn't start, and if I try to launch it from the terminal it shows this output:
╰─λ sudo oversteer -gui
Traceback (most recent call last):
  File "/usr/bin/oversteer", line 49, in <module>
    from oversteer.application import Application
  File "/usr/lib/python3.9/site-packages/oversteer/application.py", line 8, in <module>
    from xdg.BaseDirectory import *
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

I also tried to install libxdg-basedir 1.2.0-5 but the output is the same.

any clue?

Thanks

**Comment by berarma** [comment]
Are you sure `python3-xdg` or the equivalent package is installed?

**Comment by z4ri0n** [comment]
I'm net to Arch linux, and I don't know which is the exact equivalent to puthon3-xdg package.
what I installed so far are: python3-xynexdg 2012.12.24.1-11 and python-xdg 5.0.1-2
I don't have an exact match for python3-xdg unfortunately.

**Comment by isopix** [comment]
python-pyxdg

oversteer is in aur and binary package in chaotic-aur repo
It works on my machine.

Check if you have outdated python packages in system. It can be source
of problem. Pacman/makepkg is very poor at dependency tracking and
automatically do't track python dependencies properly

Output should be empty:
pacman -Qo /usr/lib/python3.8
YOu must rebuild everything if there's anything outdated.

paste output from terminal

**Comment by z4ri0n** [comment]
The problem was starship, there was a conflict with starship-git that prevented the installation of python-pyxdg.
I've just rebuilded starship and all his dependencies, it took a while but after that python-pyxdg was installed as dependency automatically, and now oversteer works fine.
Thank you very much to both for the help.

**Comment by berarma** [comment]
Great. Thanks for the confirmation.
