### ISSUE TITLE
Outdated translations for 0.6.0

### ISSUE THREAD

**Issue by berarma** [berarma/oversteer#52]
@leillo1975 and @TotalCaesar659, I'm preparing a 0.6.0 release and the Galician and Russian translations need an update. There's no hurry, I can wait but I can also do a point release if you can't update them soon.

The decission is yours.

Thanks.

**Comment by TotalCaesar659** [comment]
I'll update it in a couple of hours.

**Comment by TotalCaesar659** [comment]
@berarma After building and running `ninja -C build run`, I can't change language in preferences for testing. Here's the output:

```
ninja: Entering directory `build'                                                                                             
[0/1] Running external command run.

(oversteer:2094): GLib-GIO-CRITICAL **: 16:50:21.109: g_dbus_proxy_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Traceback (most recent call last):
  File "/home/1/oversteer/oversteer/gtk_handlers.py", line 104, in on_languages_changed
    self.controller.set_locale(widget.get_active_id())
  File "/home/1/oversteer/oversteer/gui.py", line 276, in set_locale
    self.save_preferences()
  File "/home/1/oversteer/oversteer/gui.py", line 287, in save_preferences
    'button_toggle': ','.join(map(str, self.button_config[0])),
TypeError: 'int' object is not iterable
```

**Comment by berarma** [comment]
Have you pulled the latest code. That's fixed already.

**Comment by TotalCaesar659** [comment]
Of course, Ubuntu 20.04.

**Comment by berarma** [comment]
Sorry, this was another case for an error I tried to fix.

Please, pull again, it should be fixed now.

Thanks.

**Comment by TotalCaesar659** [comment]
Great, updated locale will arrive later.

**Comment by TotalCaesar659** [comment]
@berarma Please merge https://github.com/berarma/oversteer/pull/53 and update locales.

**Comment by TotalCaesar659** [comment]
Russian translation is [updated](https://github.com/berarma/oversteer/pull/54).

**Comment by berarma** [comment]
Thanks everyone!
