### ISSUE TITLE
Support for Thrustmaster T150

### ISSUE THREAD

**Issue by Saniee** [berarma/oversteer#55]
I have a Thrustmaster T150 and would love to use this program with it, I have tried one of the drivers on github (https://github.com/scarburato/t150_driver), it seems that i need a dedicated driver specifically for for this program.

**Comment by berarma** [comment]
I need the USB product id and the driver has to support sysfs entries for the settings or it won't be very useful.

**Comment by scarburato** [comment]
The vendor is 0x044f and the product 0xb677 but at the moment there are a few problems:

The syfs attributes are partially there but the gain syfs use a different scale. The driver should be modified to be more homogeneous with the other wheels

The axis and buttons names are different so they are not shown in Oversteer (last time I tried, pressing a button non present in the interface made Oversteer crash). This problem should go away when I'll finally decide to replace the my manual parsing with the one in the hid subsystem by fixing the hid descriptor as the axis and buttons name should became more homogeneous with other hid devices.

I think that maybe it is better to solve those problems in the driver first

**Comment by berarma** [comment]
I'll add the id so at least you can test. I don't mind adding mappings now and changing them later again, at least for the axes. There's already some custom mappings. The gain scale is a slightly bigger problem.

**Comment by Saniee** [comment]
Alright, Ill test then. Thanks for this

**Comment by Saniee** [comment]
```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/pyudev/monitor.py", line 532, in run
    self._callback(device)
  File "/usr/local/lib/python3.8/dist-packages/pyudev/monitor.py", line 508, in <lambda>
    callback = lambda d: event_handler(d.action, d)
  File "/usr/lib/python3.8/site-packages/oversteer/device_manager.py", line 79, in register_event
    device.reconnect()
AttributeError: 'NoneType' object has no attribute 'reconnect'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 437, in input_thread
    self.process_events(events)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 391, in process_events
    for event in events:
  File "/usr/lib/python3.8/site-packages/oversteer/device.py", line 351, in read_events
    input_device = self.get_input_device()
  File "/usr/lib/python3.8/site-packages/oversteer/device.py", line 346, in get_input_device
    if os.access(self.dev_name, os.R_OK):
TypeError: access: path should be string, bytes or os.PathLike, not NoneType

```

1. The wheel is recognized, as far as the permissions go I rebooted as instructed but the error ^ there keeps appearing, with the popup = https://i.imgur.com/GOmLa2Q.png
2. I have tried the popup instructions too, and it now only says Error installing permissions rules. (https://i.imgur.com/PIZd3zm.png)

A little note, I have reinstalled the driver before testing. 
Another interesting thing is that the wheel is only recognized with the pedals in only. As far as I know this doesnt happen on windows since I only switched to linux recently.

Just if needed:
    Pop!_OS 20.10 (64 bit)
    Kernel Version:  5.11.0-7612-generic

**Comment by berarma** [comment]
I haven't added the wheel permissions yet, I need to look at the contents of the sysfs directory. Could you list the files in the directory where you can change the range, gain, etc.?

What's the product id without the pedals?

**Comment by Saniee** [comment]
> I haven't added the wheel permissions yet, I need to look at the contents of the sysfs directory. Could you list the files in the directory where you can change the range, gain, etc.?
```.
├── authorized
├── autocenter
├── avoid_reset_quirk
├── bcdDevice
├── bConfigurationValue
├── bDeviceClass
├── bDeviceProtocol
├── bDeviceSubClass
├── bmAttributes
├── bMaxPacketSize0
├── bMaxPower
├── bNumConfigurations
├── bNumInterfaces
├── busnum
├── configuration
├── descriptors
├── dev
├── devnum
├── devpath
├── driver -> ../../../../../bus/usb/drivers/usb
├── enable_autocenter
├── ep_00
│   ├── bEndpointAddress
│   ├── bInterval
│   ├── bLength
│   ├── bmAttributes
│   ├── direction
│   ├── interval
│   ├── power
│   │   ├── async
│   │   ├── autosuspend_delay_ms
│   │   ├── control
│   │   ├── runtime_active_kids
│   │   ├── runtime_active_time
│   │   ├── runtime_enabled
│   │   ├── runtime_status
│   │   ├── runtime_suspended_time
│   │   └── runtime_usage
│   ├── type
│   ├── uevent
│   └── wMaxPacketSize
├── firmware_node -> ../../../../LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:4e/device:4f/device:50
├── firmware_version
├── gain
├── idProduct
├── idVendor
├── input
│   └── input53
│       ├── capabilities
│       │   ├── abs
│       │   ├── ev
│       │   ├── ff
│       │   ├── key
│       │   ├── led
│       │   ├── msc
│       │   ├── rel
│       │   ├── snd
│       │   └── sw
│       ├── device -> ../../../1-1
│       ├── event24
│       │   ├── dev
│       │   ├── device -> ../../input53
│       │   ├── power
│       │   │   ├── async
│       │   │   ├── autosuspend_delay_ms
│       │   │   ├── control
│       │   │   ├── runtime_active_kids
│       │   │   ├── runtime_active_time
│       │   │   ├── runtime_enabled
│       │   │   ├── runtime_status
│       │   │   ├── runtime_suspended_time
│       │   │   └── runtime_usage
│       │   ├── subsystem -> ../../../../../../../../class/input
│       │   └── uevent
│       ├── id
│       │   ├── bustype
│       │   ├── product
│       │   ├── vendor
│       │   └── version
│       ├── inhibited
│       ├── js0
│       │   ├── dev
│       │   ├── device -> ../../input53
│       │   ├── power
│       │   │   ├── async
│       │   │   ├── autosuspend_delay_ms
│       │   │   ├── control
│       │   │   ├── runtime_active_kids
│       │   │   ├── runtime_active_time
│       │   │   ├── runtime_enabled
│       │   │   ├── runtime_status
│       │   │   ├── runtime_suspended_time
│       │   │   └── runtime_usage
│       │   ├── subsystem -> ../../../../../../../../class/input
│       │   └── uevent
│       ├── modalias
│       ├── name
│       ├── phys
│       ├── power
│       │   ├── async
│       │   ├── autosuspend_delay_ms
│       │   ├── control
│       │   ├── runtime_active_kids
│       │   ├── runtime_active_time
│       │   ├── runtime_enabled
│       │   ├── runtime_status
│       │   ├── runtime_suspended_time
│       │   └── runtime_usage
│       ├── properties
│       ├── subsystem -> ../../../../../../../class/input
│       ├── uevent
│       └── uniq
├── ltm_capable
├── manufacturer
├── maxchild
├── port -> ../1-0:1.0/usb1-port1
├── power
│   ├── active_duration
│   ├── async
│   ├── autosuspend
│   ├── autosuspend_delay_ms
│   ├── connected_duration
│   ├── control
│   ├── level
│   ├── persist
│   ├── runtime_active_kids
│   ├── runtime_active_time
│   ├── runtime_enabled
│   ├── runtime_status
│   ├── runtime_suspended_time
│   └── runtime_usage
├── product
├── quirks
├── range
├── removable
├── remove
├── rx_lanes
├── speed
├── subsystem -> ../../../../../bus/usb
├── tx_lanes
├── uevent
├── urbnum
├── version
└── 1-1:1.0
    ├── authorized
    ├── bAlternateSetting
    ├── bInterfaceClass
    ├── bInterfaceNumber
    ├── bInterfaceProtocol
    ├── bInterfaceSubClass
    ├── bNumEndpoints
    ├── driver -> ../../../../../../bus/usb/drivers/usbhid
    ├── ep_01
    │   ├── bEndpointAddress
    │   ├── bInterval
    │   ├── bLength
    │   ├── bmAttributes
    │   ├── direction
    │   ├── interval
    │   ├── power
    │   │   ├── async
    │   │   ├── autosuspend_delay_ms
    │   │   ├── control
    │   │   ├── runtime_active_kids
    │   │   ├── runtime_active_time
    │   │   ├── runtime_enabled
    │   │   ├── runtime_status
    │   │   ├── runtime_suspended_time
    │   │   └── runtime_usage
    │   ├── type
    │   ├── uevent
    │   └── wMaxPacketSize
    ├── ep_82
    │   ├── bEndpointAddress
    │   ├── bInterval
    │   ├── bLength
    │   ├── bmAttributes
    │   ├── direction
    │   ├── interval
    │   ├── power
    │   │   ├── async
    │   │   ├── autosuspend_delay_ms
    │   │   ├── control
    │   │   ├── runtime_active_kids
    │   │   ├── runtime_active_time
    │   │   ├── runtime_enabled
    │   │   ├── runtime_status
    │   │   ├── runtime_suspended_time
    │   │   └── runtime_usage
    │   ├── type
    │   ├── uevent
    │   └── wMaxPacketSize
    ├── firmware_node -> ../../../../../LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:4e/device:4f/device:50
    ├── modalias
    ├── power
    │   ├── async
    │   ├── runtime_active_kids
    │   ├── runtime_enabled
    │   ├── runtime_status
    │   └── runtime_usage
    ├── subsystem -> ../../../../../../bus/usb
    ├── supports_autosuspend
    ├── uevent
    └── 0003:044F:B677.001A
        ├── country
        ├── driver -> ../../../../../../../bus/hid/drivers/hid-t150
        ├── hidraw
        │   └── hidraw6
        │       ├── dev
        │       ├── device -> ../../../0003:044F:B677.001A
        │       ├── power
        │       │   ├── async
        │       │   ├── autosuspend_delay_ms
        │       │   ├── control
        │       │   ├── runtime_active_kids
        │       │   ├── runtime_active_time
        │       │   ├── runtime_enabled
        │       │   ├── runtime_status
        │       │   ├── runtime_suspended_time
        │       │   └── runtime_usage
        │       ├── subsystem -> ../../../../../../../../../class/hidraw
        │       └── uevent
        ├── modalias
        ├── power
        │   ├── async
        │   ├── autosuspend_delay_ms
        │   ├── control
        │   ├── runtime_active_kids
        │   ├── runtime_active_time
        │   ├── runtime_enabled
        │   ├── runtime_status
        │   ├── runtime_suspended_time
        │   └── runtime_usage
        ├── report_descriptor
        ├── subsystem -> ../../../../../../../bus/hid
        └── uevent
```
40 directories, 196 files


> What's the product id without the pedals?
 Interestingly, after fiddling around more it now registers it without the pedals. They are the same, sadly haven't checked before it wasn't registered.

+ I have noticed, `To check if the modules are loaded check the output of lsmod | grep hid-t150 and lsmod | grep hid-tminit.`, these dont output anything anymore.

**Comment by scarburato** [comment]
>I haven't added the wheel permissions yet, I need to look at the contents of the sysfs directory. Could you list the files in the directory where you can change the range, gain, etc.?

btw here you can find the sysfs entries https://github.com/scarburato/t150_driver#setting-up-the-wheel-parameters

**Comment by berarma** [comment]
I've added the udev rules. Although gain and autocenter won't work correctly with their current scales.

Also, the current minimum wheel range is 40 while TM wheels have a minimum 270. I need to fix this but it shouldn't prevent the range setting from being usable.

**Comment by Saniee** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/local/lib/python3.8/dist-packages/pyudev/monitor.py", line 532, in run
>     self._callback(device)
>   File "/usr/local/lib/python3.8/dist-packages/pyudev/monitor.py", line 508, in <lambda>
>     callback = lambda d: event_handler(d.action, d)
>   File "/usr/lib/python3.8/site-packages/oversteer/device_manager.py", line 79, in register_event
>     device.reconnect()
> AttributeError: 'NoneType' object has no attribute 'reconnect'
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 437, in input_thread
>     self.process_events(events)
>   File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 391, in process_events
>     for event in events:
>   File "/usr/lib/python3.8/site-packages/oversteer/device.py", line 351, in read_events
>     input_device = self.get_input_device()
>   File "/usr/lib/python3.8/site-packages/oversteer/device.py", line 346, in get_input_device
>     if os.access(self.dev_name, os.R_OK):
> TypeError: access: path should be string, bytes or os.PathLike, not NoneType
> ```
the error is still there, most likely just me being dumb tho

**Comment by berarma** [comment]
@Saniee, please, send me the console output when runnin `oversteer --debug`. I guess you're just running Oversteer and the error triggers.

The device name is given by the system.

**Comment by Saniee** [comment]
> @Saniee, please, send me the console output when runnin `oversteer --debug`. I guess you're just running Oversteer and the error triggers.
> 
> The device name is given by the system.

https://hatebin.com/eqnqbtyrga

**Comment by berarma** [comment]
It's trying to register a device without `ID_FOR_SEAT`. It's never happened before as far as I know. It might be related to the driver or your system.

I've pushed a new commit trying to fix the error avoid the issue. Let's see if it can recognize the device.

**Comment by scarburato** [comment]
I think the issue the driver not creating properly the input device as it misses the model and vendor id. For the moment I've pushed [this workaround](https://github.com/scarburato/t150_driver/commit/a47b1bcb0e8aeee9af8acd36ee83aee923ecd82b).

Also the `ID_FOR_SEAT` should be already be there:

```
$ udevadm info /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/input/input27
P: /devices/pci0000:00/0000:00:14.0/usb1/1-1/input/input27
L: 0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-1/input/input27
E: PRODUCT=3/44f/b677/100
E: NAME="Thrustmaster T150 steering wheel"
E: PHYS="usb-0000:00:14.0-1/input0"
E: PROP=0
E: EV=20000b
E: KEY=30000 fdb000100000000 0 0 0 0
E: ABS=30704
E: FF=11c2f0000 0
E: MODALIAS=input:b0003v044FpB677e0100-e0,1,3,15,k120,130,131,133,134,136,137,138,139,13A,13B,150,151,ra2,8,9,A,10,11,mlsf50,51,52,53,55,5A,5B,5C,60,w
E: SUBSYSTEM=input
E: USEC_INITIALIZED=60395191
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL_ID=b677
E: ID_VENDOR_ID=044f
E: ID_INPUT=1
E: ID_SERIAL=noserial
E: ID_PATH=pci-0000:00:14.0-usb-0:1
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_1
E: ID_FOR_SEAT=input-pci-0000_00_14_0-usb-0_1
E: TAGS=:seat:
```

**Comment by Saniee** [comment]
Only the `PS` Button works and is shown pressed as `B0` other buttons make an error as shown below

```Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 437, in input_thread
    self.process_events(events)
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 428, in process_events
    self.ui.safe_call(self.ui.set_btn_input, button, event.value, delay)
UnboundLocalError: local variable 'button' referenced before assignment
```

Settings like `Center Wheel` or the `Wheel range display` (this one only gives errors with the always checked) dont work mostly.

I have run the test: (for now just this, its taking long)
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/oversteer/gui.py", line 467, in end_test
    self.minimum_level = self.test.get_minimum_level()
  File "/usr/lib/python3.8/site-packages/oversteer/test.py", line 22, in get_minimum_level
    return self.minimum_level
AttributeError: 'Test' object has no attribute 'minimum_level'
```

Setting the `Rotation Range` works but defaults to 1080 thats not a big deal as far as I know, the indicators dont show the steering etc. but that is to be excepted as far as I know since its new in the program.

The `Wheel range Display` set to `Always` gives out the error below, the value is changed, but an typeError is displayed: 

```DEBUG:root:Setting range: 910
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/oversteer/gtk_handlers.py", line 81, in on_overlay_incrange_clicked
    self.ui.overlay_wheel_range.set_label(wrange)
TypeError: Must be string, not float
```

**Comment by berarma** [comment]
> Only the `PS` Button works and is shown pressed as `B0` other buttons make an error as shown below, except the `Hat` buttons. After the error is shown, the working buttons dont show as pressed.

Fixed.

> 
> Settings like `Center Wheel` or the `Wheel range display` (this one only gives errors with the always checked) dont work mostly.

The `Center Wheel` option depends on driver features.

> 
> I have run the test: (for now just this, its taking long)

I think you didn't completely follow the instructions of the test. I've fixed the test throwing an error when the user doesn't interact when required.

> 
> Setting the `Rotation Range` works but defaults to 1080 thats not a big deal as far as I know, the indicators dont show the steering etc. but that is to be excepted as far as I know since its new in the program.

It should default to the rotation range in the wheel. Might it be that the default rotation range set by the driver is 1080?

> 
> The `Wheel range Display` set to `Always` gives out the error below, the value is changed, but an typeError is displayed:

This is fixed too.

**Comment by Saniee** [comment]
> It should default to the rotation range in the wheel. Might it be that the default rotation range set by the driver is 1080?

Might be the cause.

So far its working nicely

**Comment by Saniee** [comment]
Well, hello again. Since I have some problems running the necessary programs on Linux I am transitioning back to Windows until well those programs are available there. As far as I tested, the program and the driver worked nicely and I hope someone else would test it in the free time, I hope its understandable but the lack of compatibility is making my school stuff hard on Linux. Hoping to come back when I find a way to have a little more compatibility with programs then now. Cheers and thanks for updating the program to function with this wheel.

**Comment by berarma** [comment]
I hope we see you again soon.
