### ISSUE TITLE
Support of Trustmaster T500 RS wheel using tmdrv driver

### ISSUE THREAD

**Issue by cazzoo** [berarma/oversteer#56]
Hello,

Could you please check if there are possibilities to support Thrustmaster T500 RS wheel using [tmdrv](https://github.com/her001/tmdrv) driver.
That would be brilliant. Thanks

**Comment by berarma** [comment]
Hi. I can add the device id to the list of supported devices but the driver has to provide support to be useful.

**Comment by cazzoo** [comment]
Part of the integration is being managed by #61.
Further work is anyway required from driver itself to get it working as expected

**Comment by berarma** [comment]
The PR was merged a long time ago.
