### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by mjkcz** [berarma/oversteer#57]
Hello, just yesterday, this program worked just fine, but today, when I came from school, I wanted to play American Truck Simulator, but I couldn't. When I open Oversteer from the normal program menu, it does nothing after clicked. When I try to run it with terminal, it says 'bus error (core dumped)' and doesn't run. I tried reinstalling and removing the dir, cloning and installing again. Please help! :-
![Screenshot from 2021-05-21 13-30-41](https://user-images.githubusercontent.com/73895577/119130668-cae6f280-ba38-11eb-86e3-df4e3958dad1.png)
(

**Comment by berarma** [comment]
It could be some system update, maybe from python packages or related libraries.

It might also be related to the application state. Try moving `.config/oversteer` to another directory and try again to start clean. Keep a copy of the directory so you don't loose your configuration and profiles. In case it works, please, send me a copy of the directory and I'll see what might have gone wrong.

**Comment by mjkcz** [comment]
Thank you for your help, please excuse my stupidity :P dnf update solved it just fine
