### ISSUE TITLE
command line options?

### ISSUE THREAD

**Issue by umemoni256** [berarma/oversteer#7]
Depending on the game, I would like to apply different settings to the wheel. So it would be very convenient if this could be done automatically with a script before the game starts.

Does oversteer support changing wheel settings by command line? If so, where can I find the documentation? If not, would you consider adding this feature to your tool?

**Comment by berarma** [comment]
Yes. Try --help to see avalaible options.

**Comment by umemoni256** [comment]
Exactly what I was looking for. Thanks!

**Comment by fuzunspm** [comment]
@berarma Is it possible increase or decrease ff gain with commands?

for example:
`oversteer --ff-gain -5`

**Comment by berarma** [comment]
> @berarma Is it possible increase or decrease ff gain with commands?
> 
> for example:
> `oversteer --ff-gain -5`

No, it wouldn't work for most cases. Normally, drivers don't allow reading the current value nor making relative changes.

**Comment by fuzunspm** [comment]
is it then possible to get current value? I may create a custom command then

**Comment by berarma** [comment]
> is it then possible to get current value? I may create a custom command then

That's the issue. Which device/driver are you using?

**Comment by fuzunspm** [comment]
g29/new-lg4ff
