### ISSUE TITLE
Unable to do permissions fix

### ISSUE THREAD

**Issue by Frappyy** [berarma/oversteer#70]
Everything seemed to install and run fine until I got asked about the permissions thing. I clicked OK to fix it for me which ended up failing. When I tried doing it manually, it turns out that `/usr/local/share/oversteer/udev` didn't even exist in the first place to make the change. When I press cancel, it does detect all my inputs though.

Using Ubuntu 21.04 with Logitech G29 + H-Shifter.

**Comment by berarma** [comment]
That feature is broken in the master branch but it shouldn't be needed anymore. The permissions file will be installed automatically along Oversteer, it should work after a reboot.

**Comment by Frappyy** [comment]
Ah, okay. Thanks.
