### ISSUE TITLE
G920 Help

### ISSUE THREAD

**Issue by petobena** [berarma/oversteer#71]
Hi,
sorry, this is not the right place to ask.

Can somebody help me to get work my G920 on Ubuntu 20.04?
I have connected it, the led blink. but nothing happened, also in oversteer. The device will be shown in the app.

ls -lR /dev/input/

/dev/input/:
crw-rw----  1 root input 13, 87 aug  5 21:55 event2
crw-rw-r--+ 1 root input 13,  0 aug  5 21:55 js0

/dev/input/by-id:
lrwxrwxrwx 1 root root 9 aug  5 21:55 usb-Logitech_G920_Driving_Force_Racing_Wheel_for_Xbox_One_000024a0dc026cf0-event-joystick -> ../event2
lrwxrwxrwx 1 root root 6 aug  5 21:55 usb-Logitech_G920_Driving_Force_Racing_Wheel_for_Xbox_One_000024a0dc026cf0-joystick -> ../js0

/dev/input/by-path:
lrwxrwxrwx 1 root root 9 aug  5 21:55 pci-0000:00:16.0-usb-0:2:1.0-event-joystick -> ../event2
lrwxrwxrwx 1 root root 6 aug  5 21:55 pci-0000:00:16.0-usb-0:2:1.0-joystick -> ../js0

Thanks a lot for the help !!! :)

**Comment by isopix** [comment]
Check if you are in 'input' group, by typing 'id', because only thrn you
will be able to use force feedback on your system.

BTW, What does it mean 'will be shown in the app'?
5 sie 2021 22:04 "Peto" ***@***.***> napisał(a):

**Comment by petobena** [comment]
@isopix 
in "id" im not in, only in "id peto"

peto@peto-pc:~$ id
uid=1000(peto) gid=1000(peto) skupiny=1000(peto),4(adm),5(tty),20(dialout),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),131(lxd),132(sambashare)
peto@peto-pc:~$ id peto
uid=1000(peto) gid=1000(peto) skupiny=1000(peto),4(adm),5(tty),20(dialout),24(cdrom),27(sudo),30(dip),46(plugdev),107(input),120(lpadmin),131(lxd),132(sambashare)
peto@peto-pc:~$ whoami 
peto


I meant in the app is the wheel listened
![obrázok](https://user-images.githubusercontent.com/1074366/128417254-e672fc1b-b9ce-4091-8240-f78d44d1757f.png)

**Comment by berarma** [comment]
What's the issue? Your wheel is recognized by Oversteer but... What doesn't work?
