### ISSUE TITLE
Thrustmaster T300 RS T2PA pedals incorrectly showing up as Clutch and Brake

### ISSUE THREAD

**Issue by ric2b** [berarma/oversteer#73]
(Related to https://github.com/Kimplul/hid-tmff2/issues/24, since Oversteer is manually remapping the pedals for this wheel in a way that looks incorrect)

[This commit](https://github.com/berarma/oversteer/commit/55db3f6da91b16be0bd7e5c04b61e31a550f08e3) introduced the re-mapping for the TM_T300RS, although from looking at the linked issue (https://github.com/berarma/oversteer/issues/40) the change seems to have been made to fix an issue with a Logitech Momo wheel, it's not clear to me if the T300 RS was tested at the time.

Oversteer seems to [normalize the pedal codes](https://github.com/berarma/oversteer/blob/0.6.0/oversteer/gui.py#L399) like so:
- `ABS_Y` -> accelerator
- `ABS_Z` -> brake
- `ABS_RZ` -> clutch

On my T300 RS with T2PA pedals the brake is `ABS_Y` and the throttle is `ABS_RZ`.

Which means for the for the T300 RS with T2PA pedals [device.py](https://github.com/berarma/oversteer/blob/0.6.0/oversteer/device.py#L368) should do `ABS_Y` -> `ABS_Z` and `ABS_RZ` -> `ABS_Y`, although I don' t know if it would cause issues for people using other pedals with the same weel:

```diff
-           elif self.usb_id in [self.device_manager.LG_G25, self.device_manager.LG_G27, self.device_manager.LG_G29, self.device_manager.TM_T300RS]:
+           elif self.usb_id in [self.device_manager.LG_G25, self.device_manager.LG_G27, self.device_manager.LG_G29]:
                if event.code == ecodes.ABS_Y:
                    event.code = ecodes.ABS_RZ
                elif event.code == ecodes.ABS_Z:
                    event.code = ecodes.ABS_Y
                elif event.code == ecodes.ABS_RZ:
                    event.code = ecodes.ABS_Z
+           elif self.usb_id in [self.device_manager.TM_T300RS]:
+               if event.code == ecodes.ABS_Y:
+                   event.code = ecodes.ABS_Z
+               elif event.code == ecodes.ABS_Z:  # Doesn't exist with T2PA, not sure if this is how the clutch shows up
+                   event.code = ecodes.ABS_RZ
+               elif event.code == ecodes.ABS_RZ:
+                   event.code = ecodes.ABS_Y
```

**Comment by berarma** [comment]
Those pedals don't match any mapping I've seen to date. If I change the current mapping it would work for your pedals but would be incorrect for other ones. I should be able to tell which pedals are connected to the wheel.

Anyway, be aware that this doesn't affect how the wheel works or how games map the pedals. It's only internal to Oversteer and the only effect is that it will show incorrectly in the UI.

I'd like to fix it but I'd need to know which pedals are connected.

@Kimplul, do you know some way to tell which pedals are connected to the wheel?

**Comment by Kimplul** [comment]
At the moment, no. I suspect it's not impossible, as there's still a lot of setup packets between Windows and the wheel that I'm not sure the function of. Pedal data could easily be in there somewhere, but I would need a second pedal set or someone willing to capture some packets and test out 'experimental' features.

@ric2b if you have the time and energy to help me I would greatly appreciate it.

**Comment by ric2b** [comment]
I'm definitely interested in helping, yes :)

**Comment by Kimplul** [comment]
Yep, that's more or less it. I would mainly need the packets that are used to set up the wheel, and then I could probably compare where your packets differ from mine and maybe figure out what the differences mean.

I would suggest going into details in some other thread or on discord, as this isn't strictly related to oversteer.
