### ISSUE TITLE
Trying to combine pedals for Logitech WingMan Formula GP

### ISSUE THREAD

**Issue by Jordi234** [berarma/oversteer#75]
Hi!

I'm trying to configure my "old" racing wheel formula gp. I'm on EndeavourOS for now. I installed Oversteer from the AUR and apparently is working, but I don't understand why the combine pedals option on one axis is greyed out, I can't change anything.

Well, I would to try this option to play another "old" game, ColinMcRae Dirt (first version), and in game the pedals only appears in digital mode, I configure brake and gas, and seems a normal button of gamepad, not an analogic axis.
What I can do to solve this problem? I can't found any info for this issue.

Thanks in advance.

**Comment by berarma** [comment]
It seems more like an issue in the game that Oversteer won't fix.

I'd like to look into the combine pedals switch being disabled, it should work. I'll try to test it even though I don't have that wheel.

**Comment by Jordi234** [comment]
Yes, seems an in-Game issue. I have Toca Race Driver 3 and I not have any problem with analog controls, but in Dirt, is very strange to play with digital pedals....
I don't understand this "I'd like to look", you need a capture? This is how the program appears, and I don't know if I have left something to install or something:
![Screenshot_20210909_055553](https://user-images.githubusercontent.com/50656610/132620358-5f3783cd-d6db-4561-8cbd-3effa62c02cc.png)

Thanks.

**Comment by berarma** [comment]
Yes, the screenshot is useful, now I'll try to reproduce the issue with my wheel.

**Comment by Jordi234** [comment]
I switched to Kubuntu but the problem is the same. Kubuntu seems work better with Steam than Arch.

**Comment by berarma** [comment]
Are you still having this issue? It should be fixed by installing a newer version of Oversteer.

**Comment by Jordi234** [comment]
Sorry to revive this old post, but I still having the problem. On this 2022 I uninstalled this old games and I completely forgot to say something here, but now I'm testing it again and Oversteel on Debian 12 have the same situation, all is greyed out. Testing with jstest-gtk I can configure things for my (old) wheel but with your program I can't do anything. Is strange. With ETS2 teh weel works perfect configured with jstest-gtk.
Thanks and sorry for forget this post.
