### ISSUE TITLE
Raceroom Racing Experience and wheel rotation

### ISSUE THREAD

**Issue by fuzunspm** [berarma/oversteer#79]
Hi,

Raceroom Racing Experience won't automatically switch wheel rotation unlike other games. It could be game itself has the issue i don't know but normally let's say driving a car with 540 degree of wheel should be 1:1 map but it's not unless I manually change wheel rotation from oversteer to 540 degree.

Additionally It could be very good to increase/decrease rotation value by single digits values like 368 degree

**Comment by berarma** [comment]
I think this is an issue in Raceroom or Proton, not Oversteer.

In case you don't know, Oversteer provides a tool to let you change the wheel range from the wheel buttons.

Changing the range less than 10 degrees seems like a very small change that I don't think is that noticeable on the screen. What do others think?
