### ISSUE TITLE
Can't resize application.

### ISSUE THREAD

**Issue by IOBYTE** [berarma/oversteer#8]
I just upgraded oversteer and installed new-lg4ff and I can't resize the application.  The maximize button doesn't work right (it makes the vertical size larger than the display) and I can't make the application smaller by grabbing the corners or edges.  The initial size is taller than the display so the bottom is always cut off.

There also seems to be a dead band for the steering display when centered.

I'm running ubuntu 18.04 with an ultra wide display.

Should I have uninstalled the old version before installing the newer one? Uninstalling and installing the new version doesn't help.

**Comment by berarma** [comment]
Please, could you post screenshots of the application when launched and after maximizing?

**Comment by berarma** [comment]
I've made some changes to the layout and disabled the maximize function because the layout doesn't work well with it.

I've removed the dead band too.

Please, check the changes and post screenshots of any persisting issue.

Thanks.

**Comment by IOBYTE** [comment]
Here are 2 pictures. The first is just launched and the second is with the app moved up as far as possible.  The app is larger than the available screen space in both cases.
![JustLaunched](https://user-images.githubusercontent.com/1819479/72816893-d9e84580-3c36-11ea-8ce6-4b0a1e5a577d.png)
![MovedUp](https://user-images.githubusercontent.com/1819479/72816921-e79dcb00-3c36-11ea-80e2-1ac8a25dedcb.png)

**Comment by berarma** [comment]
Wow! That's a pretty broken UI.

I see the Debian logo, but you reported as using Ubuntu 18.04.

The problem could be a very old or broken version of GTK3, or maybe the Python bindings. Maybe the gtk theme. I don't even know where to start to try to reproduce what you have there.

**Comment by IOBYTE** [comment]
It's just ubuntu 18.04 running gnome shell to get the old classic desktop.

**Comment by berarma** [comment]
How have you made gnome shell have that old classic desktop look?

**Comment by IOBYTE** [comment]
I'm pretty sure I use gnome flashback.

**Comment by IOBYTE** [comment]
I could have also used gnome-shell-extensions.  I honestly don't remember.  I have gnome-shell-extensions deb installed so that's probably what I'm using.  I think I used gnome flashback on 16.04 because that's all that was available then but gnome-shell-extensions is the newer way to get the old classic desktop.

**Comment by berarma** [comment]
@IOBYTE, are you still experiencing the problem or has it gone away?

**Comment by IOBYTE** [comment]
Nothing has changed.  It starts up larger than the available vertical screen space (bottom is chopped off) and there is no resize button and you can't grab the sides to resize it.

**Comment by IOBYTE** [comment]
I upgraded ubuntu from 18.04 to 20.04 and the gui is now smaller than the screen.  I still can't resize it but I can see all of it now.

**Comment by berarma** [comment]
Resizing is disabled. Is it still as broken as it was or does it look right now?

**Comment by berarma** [comment]
From the last comment I'm guessing this is fixed.
