### ISSUE TITLE
Support for Simagic Wheels / Alpha

### ISSUE THREAD

**Issue by obirkedal** [berarma/oversteer#82]
Hi, with the addition of support for Fanatec based wheels, i was curious if there is interest/possibility for supporting Simagic devices.
The Alpha unit i have is being detected by my Manjaro install by default, there is simply no FFB support.

Im not very experienced with linux or development, however more than willing to help with testing if needed.

**Comment by berarma** [comment]
Oversteer doesn't provide low-level hardware support. Adding FFB support would require work on a Linux driver.

I can add the wheel to Oversteer so it gets detected but FFB will still not work.

**Comment by JacKeTUs** [comment]
Hello, i've got Simagic Alpha series wheelbase working with FFB
https://github.com/JacKeTUs/simagic-ff

Later i plan to write interfaces to Oversteer, and make a PR for it
