### ISSUE TITLE
G27 not detected by Oversteer

### ISSUE THREAD

**Issue by mubbery** [berarma/oversteer#84]
Using the latest Pop_OS. All up to date. PC is a Ryzen 3700X on an ASUS X570 mobo, so not an old machine or anything out of the ordinary.

The Oversteer app does not show any devices listed. I have tried a USB 2 and USB 3 port.
My G29 wheel is showing in the list of connected USB devices. I
lsusb shown the device as:
Bus 003 Device 003: ID 046d:c260 Logitech, Inc. G29 Driving Force Racing Wheel [PS4]

I have also tried installing new-lg4ff but that did not help.

I'm guessing I'm being a noob but I have followed all instructions and this is basically a new OS with Steam, Wreckfest, and Oversteer installed.

If you have a forum or discord for me to direct my query please let me know. If you would like logs or any other information from me feel free to message me.

**Comment by berarma** [comment]
It has to be in PS3 mode to work. Toggle the switch in the wheel and reconnect.

**Comment by mubbery** [comment]
Typo'd G27 should have said G29 but also has that switch. Never noticed it. What a dummy :)
