### ISSUE TITLE
Locale not supported

### ISSUE THREAD

**Issue by irseny** [berarma/oversteer#87]
When running oversteer in a desktop environment I get an exception in the auto generated main executable:
```
$ oversteer --help
Traceback (most recent call last):
  File "/usr/local/bin/oversteer", line 49, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
I suspect this is related to running english language with german number formatting.
My proposed solution is to surround the failing call with try ... except to make the error less severe
```
try:
    locale.setlocale(locale.LC_ALL, '')
except locale.Error as e:
    print(str(e))
```
But where does the code actually come from before auto generation?

**Comment by berarma** [comment]
Can you paste the output of the locale command?

**Comment by irseny** [comment]
Output is  as follows:
```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_DE.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_DE.UTF-8"
LC_NUMERIC="en_DE.UTF-8"
LC_TIME="en_DE.UTF-8"
LC_COLLATE="en_DE.UTF-8"
LC_MONETARY="en_DE.UTF-8"
LC_MESSAGES="en_DE.UTF-8"
LC_PAPER="en_DE.UTF-8"
LC_NAME="en_DE.UTF-8"
LC_ADDRESS="en_DE.UTF-8"
LC_TELEPHONE="en_DE.UTF-8"
LC_MEASUREMENT="en_DE.UTF-8"
LC_IDENTIFICATION="en_DE.UTF-8"
LC_ALL=
```
Do you spot anything special, is my system broken?

BTW after applying my fix I get one warning by GTK regarding locale issues
```
(oversteer:19512): Gtk-WARNING **: 16:32:07.020: Locale not supported by C library.
        Using the fallback 'C' locale.
```

**Comment by berarma** [comment]
It seems your English locale hasn't been generated. You should have both en_DE.UTF-8 and en_US.UTF-8 in your system. Check with `locale -a`.

**Comment by irseny** [comment]
I do not seem to have them
```
$ locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
C.UTF-8
POSIX
de_DE.utf8
en_US.utf8
```
and generating with
`locale-gen
regenerates en_US.utf8 and de_DE.utf8
-----------------------------------------------------
While writing this message i fixed the problem and created my own locale

**Comment by berarma** [comment]
It seems you used a custom locale string without generating the locale data files. Generating them fixed the issue.
