### ISSUE TITLE
Does not find Wheel without sudo

### ISSUE THREAD

**Issue by Gonzo2O28** [berarma/oversteer#9]
Oversteer does not find the wheel without sudo.
Plus after changing some settings and reinstalling windows, in windows 10 it was detected as gt driving force - different wheel. I never had that before, using that g27 for almost ten years now. i had to manually force the g27 driver in windows to fix this. So something might be wrong here.

using the package from the aur under arch linux.

**Comment by berarma** [comment]
Can you use the wheel on any other Linux software without using sudo?

There's nothing I can do about the Windows issues. You can always reset the wheel by unplugging it from the power adapter.

**Comment by mysexyDate24com** [comment]
All other tools show the wheel immediately as /dev/input/js0 iirc.Am 10.02.2020 15:39 schrieb Bernat <notifications@github.com>:Can you use the wheel on any other Linux software without using sudo?
There's nothing I can do about the Windows issues. You can always reset the wheel by unplugging it from the power adapter.

**Comment by mysexyDate24com** [comment]
> Can you use the wheel on any other Linux software without using sudo?
> 
> There's nothing I can do about the Windows issues. You can always reset the wheel by unplugging it from the power adapter.

The Windows issue might have something to do with the settings your tool wrote into the g27 wheel under linux. in ten years this never happened before, might be coincidence, but i doubt it.

**Comment by berarma** [comment]
> All other tools show the wheel immediately as /dev/input/js0

That's the old joystick interface. Overtools, and most current software use the evdev interface (/dev/input/eventX).

> The Windows issue might have something to do with the settings your tool wrote into the g27 wheel under linux. in ten years this never happened before, might be coincidence, but i doubt it.

Please, read the disclaimer in the README. If you're not happy with Oversteer, don't use it.

**Comment by mysexyDate24com** [comment]
Not happy? I am reporting a bug, thats all!
The new version which just came up has the same issue. My user is in the input group. 

l /dev/input/event7
crw-rw----+ 1 root input 13, 71 11. Feb 14:06 /dev/input/event7

sudo oversteer --list
Devices found:
  /dev/input/event7: G27 Racing Wheel (input-pci-0000_06_00_1-usb-0_3_3_3_1_0)

oversteer --list
Devices found:

**Comment by Gonzo2O28** [comment]
as root

oversteer --debug
DEBUG:root:Devices:{'input-pci-0000_06_00_1-usb-0_3_3_3_1_0': {'id': 'input-pci-0000_06_00_1-usb-0_3_3_3_1_0', 'path': '/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:06:00.1/usb1/1-3/1-3.3/1-3.3.3/1-3.3.3:1.0/0003:046D:C29B.000C/input/input37/device', 'name': 'G27 Racing Wheel', 'dev': '/dev/input/event7'}}
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:root:Setting range: 900
DEBUG:root:Setting range: 900

as user:

oversteer --debug
DEBUG:root:Devices:{}

**Comment by berarma** [comment]
Please, try these commands as a normal user and as root and paste here the output:

`ffcfstress -d /dev/input/event7`

`udevadm info /dev/input/event7`

The device `/dev/input/event7` should be your wheel, please check that.

The `ffcfstress` command can be found in the `joystick`package in Debian. Look for it in Arch.

Please, attach the full ouput.

I'm trying to help you. Windows issues should stay in Windows. Oversteer can't be blamed for Windows faults.

**Comment by Gonzo2O28** [comment]
ffcfstress -d /dev/input/event11

        position                   center                     force
<+**********|-----------> ************|-----------> <---------+*|----------->^C⏎  


The Windows-Issue appeared after your tool wrote settings into the wheel, so i am not sure that this is a windows-only issue. 

ffcstress works as expected without sudo.
Regards

**Comment by Gonzo2O28** [comment]
hm, i fixed it with.

sudo cp /usr/share/oversteer/udev/99-logitech-wheel-perms.rules /etc/udev/rules.d/

seems to work now. the file /etc/udev/rules.d/99-logitech-wheel-perms.rules differs a lot from that file in /usr/share/oversteer/udev/.

**Comment by berarma** [comment]
Do you have a copy of the old file to share with us? The problem is there then.

**Comment by Gonzo2O28** [comment]
No, sorry i overwrote it.
It was installed from the AUR and contained only a couple of Logitech Wheels ~ 3-4.
That file i copied over from /usr/share/oversteer/udev/99-logitech-wheel-perms.rules contains 13 entries.

**Comment by berarma** [comment]
It should be the old file shipped with Oversteer. It has never caused that problem. The line you pasted is missing an asterisk (*), could it be a copy/paste error?

**Comment by Gonzo2O28** [comment]
hm, i dont think so, but might be. 
before i had an intel system and oversteer worked out of the box, i immediately start to love it along with the new g27 kernel driver. now with the new system ryzen 3950x/x570 i completely reinstalled my arch and moved from xfce to kde plasma i ran into this issue.
