### ISSUE TITLE
you don't have the requiered permission to change your wheel settings

### ISSUE THREAD

**Issue by cerotonine** [berarma/oversteer#92]
Hi, I'm sorry if this is kinda dumb, I'm new on linux and it has been a long road, learning lots of stuff by breaking everything.
I tried following the "readme" that it's provided here for the installation, and after doing everything as it says i get the error when launching oversteer "you don't have the requiered permission to change your wheel settings". I tried copying the files that are supposed to give you permission to modify the settings to /lib/udev/rules.d and such, i even searched on /etc/ and deleted the only 99-logitech-wheel.rules that i had, and yet i can't get it to work, idk what i'm doing wrong if someone can help me pls. I'm also on Pop!OS in case it helps. Thanks!

PS: Oversteer recognizes my wheel and everything fine but with this error i can't even create a profile and such, hence why i'm trying to fix it.
PS.2: The image on /lib/ shows no files related to oversteer because i deleted them to try and see if i don't get the same error, but it didn't work
![gnome-shell-screenshot-d84id4](https://user-images.githubusercontent.com/98622158/151631123-7952b78f-23a9-4319-9921-4a12bd20ca8d.png)
![Screenshot-20220128193537-630x237](https://user-images.githubusercontent.com/98622158/151631126-179ae2aa-3f03-467d-840c-bd2403c39e78.png)
![Screenshot-20220128193612-1001x367](https://user-images.githubusercontent.com/98622158/151631128-95d13fcf-0016-4d23-8826-896ed751507b.png)
.

**Comment by cerotonine** [comment]
![Screenshot-20220128193644-1003x780](https://user-images.githubusercontent.com/98622158/151634930-d69d1b21-0d82-4956-8658-73d528f69214.png)
forgot to upload this one mb

**Comment by berarma** [comment]
The install step will put the udev files where they should be. You need to reboot after that.

**Comment by cerotonine** [comment]
> The install step will put the udev files where they should be. You need to reboot after that.

Ohh, you're right my bad, Thank you so much for answering!

**Comment by berarma** [comment]
No problem. I've clarified that step in the README.
