### ISSUE TITLE
Multiple wheels of the same model?

### ISSUE THREAD

**Issue by Nomagno** [berarma/oversteer#98]
Greetings. Would I be able to plug in and simultaneously use multiple wheel+pedal sets of the exact same type (DFGT in this case)?

**Comment by berarma** [comment]
I guess you should be able to do it but this depends only on the driver module.

Oversteer should be able to handle them but not simultaneously. I mean, you should configure them one at a time and settings should persist even if you change the selected wheel. Some features like the OSD and using the wheel buttons to change the wheel range won't work simultaneously on both wheels. You could try running two instances of Oversteer, one for each wheel but I don't know how well it'll work.

**Comment by Nomagno** [comment]
I can confirm it works perfectly configuring one, switching, then the other. Thanks!

**Comment by berarma** [comment]
Thanks for reporting!
