### ISSUE TITLE
`oversteer -p myprofile -g "%command%"` works but `oversteer -p myprofile "%command%"` does not.

### ISSUE THREAD

**Issue by kevenwyld** [berarma/oversteer#99]
I apologize if I'm missing something obvious.... I'm trying to set up oversteer to load profiles silently on game launch with steam.  The help output implies that I can pass a command as the last (positional) argument however this only seems to work when using the `-g` option.

Testing on the command line I can run for example:

`oversteer -p windows_defaults -g xeyes`  Launches the oversteer gui and then xeyes.  When xeyes is closed oversteer closes as well.

However when I omit the `-g` xeyes doesn't launch despite the exit status being 0:

`oversteer -p windows_defaults xeyes`  No output, xeyes does not start, and the exit status is 0

Is this expected behavior?

Thanks!

**Comment by berarma** [comment]
It's how it has worked until now but not the best behavior. I've changed it in master. Thanks for the report.
